'use client'

import { cn } from '@/lib/utils'
import { Brain, Sparkles, Cpu, Zap } from 'lucide-react'

type BadgeVariant = 'header' | 'inline' | 'card' | 'minimal' | 'cta'

interface AdaptiveEngineBadgeProps {
  variant?: BadgeVariant
  message?: string
  className?: string
  showIcon?: boolean
}

/**
 * AdaptiveEngineBadge - Branding component for the SpartanLab Adaptive Training Engine
 * Used throughout the platform to communicate that the system analyzes training data
 * and generates intelligent recommendations.
 */
export function AdaptiveEngineBadge({ 
  variant = 'inline', 
  message,
  className,
  showIcon = true 
}: AdaptiveEngineBadgeProps) {
  
  if (variant === 'header') {
    return (
      <div className={cn(
        "relative overflow-hidden rounded-xl bg-gradient-to-r from-[#1A1F26] via-[#1E2330] to-[#1A1F26] border border-[#2B313A] p-4 sm:p-5",
        className
      )}>
        {/* Subtle gradient accent */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#C1121F]/5 via-transparent to-[#C1121F]/5 pointer-events-none" />
        
        <div className="relative flex items-center gap-3 sm:gap-4">
          <div className="flex-shrink-0 w-10 h-10 sm:w-11 sm:h-11 rounded-xl bg-gradient-to-br from-[#C1121F]/20 to-[#C1121F]/5 border border-[#C1121F]/20 flex items-center justify-center">
            <Brain className="w-5 h-5 sm:w-6 sm:h-6 text-[#C1121F]" />
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h2 className="text-sm sm:text-base font-semibold text-[#E6E9EF] tracking-tight">
                Adaptive Training Engine
              </h2>
              <span className="hidden sm:inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium bg-[#C1121F]/10 text-[#C1121F] border border-[#C1121F]/20">
                <Zap className="w-2.5 h-2.5" />
                ACTIVE
              </span>
            </div>
            <p className="text-xs sm:text-sm text-[#6B7280] mt-0.5 leading-relaxed">
              {message || 'Analyzing your training data to generate adaptive recommendations and insights.'}
            </p>
          </div>
        </div>
      </div>
    )
  }

  if (variant === 'card') {
    return (
      <div className={cn(
        "flex items-center gap-2 px-3 py-2 rounded-lg bg-[#1A1F26]/50 border border-[#2B313A]/50",
        className
      )}>
        {showIcon && (
          <Cpu className="w-3.5 h-3.5 text-[#C1121F]/70 flex-shrink-0" />
        )}
        <p className="text-xs text-[#6B7280]">
          {message || 'Powered by the Adaptive Training Engine'}
        </p>
      </div>
    )
  }

  if (variant === 'minimal') {
    return (
      <div className={cn(
        "flex items-center gap-1.5 text-[#6B7280]",
        className
      )}>
        {showIcon && <Sparkles className="w-3 h-3 text-[#C1121F]/60" />}
        <span className="text-[10px] sm:text-xs">
          {message || 'Adaptive Training Engine'}
        </span>
      </div>
    )
  }

  if (variant === 'cta') {
    return (
      <div className={cn(
        "mt-6 p-4 rounded-lg bg-gradient-to-r from-[#1A1F26] to-[#1E2330] border border-[#2B313A]",
        className
      )}>
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0 w-8 h-8 rounded-lg bg-[#C1121F]/10 border border-[#C1121F]/20 flex items-center justify-center">
            <Brain className="w-4 h-4 text-[#C1121F]" />
          </div>
          <div>
            <p className="text-sm font-medium text-[#E6E9EF] mb-1">
              Want deeper adaptive insights?
            </p>
            <p className="text-xs text-[#6B7280]">
              {message || 'Use the SpartanLab Adaptive Training Engine inside your training dashboard for personalized recommendations.'}
            </p>
          </div>
        </div>
      </div>
    )
  }

  // Default: inline variant
  return (
    <div className={cn(
      "inline-flex items-center gap-1.5 text-[#6B7280]",
      className
    )}>
      {showIcon && <Cpu className="w-3 h-3 text-[#C1121F]/60 flex-shrink-0" />}
      <span className="text-[10px] sm:text-xs">
        {message || 'Generated by the Adaptive Training Engine'}
      </span>
    </div>
  )
}

/**
 * Preset messages for different contexts
 */
export const ENGINE_MESSAGES = {
  dashboard: 'Analyzing your training data to generate adaptive recommendations and insights.',
  program: 'Generated by the SpartanLab Adaptive Training Engine',
  programHelper: 'Your program adapts automatically as SpartanLab collects more training signals.',
  adjustment: 'Adjustment generated by the Adaptive Training Engine',
  forecast: 'Forecast powered by the Adaptive Training Engine',
  insight: 'Insight generated from your training signals',
  limiter: 'Analysis powered by the Adaptive Training Engine',
  recovery: 'Recovery status analyzed by the Adaptive Training Engine',
  tool: 'Use the SpartanLab Adaptive Training Engine inside your training dashboard for personalized recommendations.',
  toolSignal: 'This result is one signal used by the SpartanLab Adaptive Training Engine.',
  trainingSignals: 'Generated from your recent training signals.',
} as const

/**
 * SensorEngineVisualization - Visual diagram showing how athlete sensors
 * feed into the Adaptive Training Engine to generate insights
 */
interface SensorEngineVisualizationProps {
  variant?: 'full' | 'compact'
  className?: string
}

export function SensorEngineVisualization({ 
  variant = 'full',
  className 
}: SensorEngineVisualizationProps) {
  const sensors = ['Skills', 'Strength', 'RPE', 'Recovery']
  const outputs = ['Training Insights', 'Daily Adjustments', 'Progress Forecast']

  if (variant === 'compact') {
    return (
      <div className={cn(
        "flex flex-col items-center gap-2 py-3 px-4 rounded-lg bg-[#1A1F26]/30 border border-[#2B313A]/50",
        className
      )}>
        <div className="flex items-center gap-2 text-[10px] text-[#6B7280]">
          <span className="text-[#A4ACB8]">Sensors</span>
          <span className="text-[#3A4553]">→</span>
          <span className="text-[#C1121F]">Engine</span>
          <span className="text-[#3A4553]">→</span>
          <span className="text-[#A4ACB8]">Insights</span>
        </div>
      </div>
    )
  }

  return (
    <div className={cn(
      "relative rounded-xl bg-gradient-to-b from-[#1A1F26] to-[#0F1115] border border-[#2B313A]/70 overflow-hidden",
      className
    )}>
      {/* Subtle background pattern */}
      <div className="absolute inset-0 opacity-[0.02] pointer-events-none" 
        style={{ 
          backgroundImage: 'radial-gradient(circle at 1px 1px, #fff 1px, transparent 0)',
          backgroundSize: '24px 24px'
        }} 
      />

      <div className="relative p-4 sm:p-5">
        {/* Three-column layout on desktop, stacked on mobile */}
        <div className="flex flex-col sm:flex-row items-center gap-4 sm:gap-6">
          
          {/* Athlete Sensors Column */}
          <div className="flex-1 w-full sm:w-auto text-center sm:text-left">
            <div className="flex items-center justify-center sm:justify-start gap-1.5 mb-2">
              <div className="w-1.5 h-1.5 rounded-full bg-[#4ADE80]/60" />
              <span className="text-[10px] font-medium uppercase tracking-wider text-[#6B7280]">
                Athlete Sensors
              </span>
            </div>
            <div className="flex flex-wrap items-center justify-center sm:justify-start gap-1.5">
              {sensors.map((sensor, i) => (
                <span 
                  key={sensor}
                  className="inline-flex items-center px-2 py-1 rounded-md text-[11px] font-medium bg-[#2B313A]/50 text-[#A4ACB8] border border-[#3A4553]/30"
                >
                  {sensor}
                </span>
              ))}
            </div>
          </div>

          {/* Flow Arrow + Engine */}
          <div className="flex flex-col items-center gap-2 py-2 sm:py-0">
            {/* Arrow Down (mobile) / Right (desktop) */}
            <div className="flex items-center gap-1 text-[#3A4553]">
              <svg className="w-4 h-4 sm:hidden" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 5v14M19 12l-7 7-7-7" />
              </svg>
              <svg className="w-4 h-4 hidden sm:block" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M5 12h14M12 5l7 7-7 7" />
              </svg>
            </div>
            
            {/* Engine Badge */}
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-gradient-to-r from-[#C1121F]/10 to-[#C1121F]/5 border border-[#C1121F]/20">
              <Brain className="w-4 h-4 text-[#C1121F]" />
              <span className="text-xs font-semibold text-[#E6E9EF] whitespace-nowrap">
                Adaptive Engine
              </span>
            </div>

            {/* Arrow Down (mobile) / Right (desktop) */}
            <div className="flex items-center gap-1 text-[#3A4553]">
              <svg className="w-4 h-4 sm:hidden" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 5v14M19 12l-7 7-7-7" />
              </svg>
              <svg className="w-4 h-4 hidden sm:block" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M5 12h14M12 5l7 7-7 7" />
              </svg>
            </div>
          </div>

          {/* Training Outputs Column */}
          <div className="flex-1 w-full sm:w-auto text-center sm:text-right">
            <div className="flex items-center justify-center sm:justify-end gap-1.5 mb-2">
              <div className="w-1.5 h-1.5 rounded-full bg-[#C1121F]/60" />
              <span className="text-[10px] font-medium uppercase tracking-wider text-[#6B7280]">
                Training Output
              </span>
            </div>
            <div className="flex flex-wrap items-center justify-center sm:justify-end gap-1.5">
              {outputs.map((output) => (
                <span 
                  key={output}
                  className="inline-flex items-center px-2 py-1 rounded-md text-[11px] font-medium bg-[#C1121F]/10 text-[#E6E9EF] border border-[#C1121F]/20"
                >
                  {output}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Subtle footer explanation */}
        <div className="mt-4 pt-3 border-t border-[#2B313A]/50 text-center">
          <p className="text-[10px] text-[#6B7280]">
            SpartanLab continuously analyzes your training signals to generate personalized insights
          </p>
        </div>
      </div>
    </div>
  )
}

/**
 * SignalIndicator - Small inline indicator showing this is a training signal
 */
interface SignalIndicatorProps {
  message?: string
  className?: string
}

export function SignalIndicator({ message, className }: SignalIndicatorProps) {
  return (
    <div className={cn(
      "flex items-center gap-1.5 text-[#6B7280]",
      className
    )}>
      <div className="flex items-center gap-0.5">
        <div className="w-1 h-1 rounded-full bg-[#4ADE80]/60" />
        <div className="w-1 h-1 rounded-full bg-[#FACC15]/60" />
        <div className="w-1 h-1 rounded-full bg-[#C1121F]/60" />
      </div>
      <span className="text-[10px]">
        {message || 'Training signal'}
      </span>
    </div>
  )
}
