/**
 * SPARTAN LAB - FINAL PHASE: STABILITY LOCK + PRODUCTION READINESS
 * 
 * This file documents the production-locked architecture and canonical paths.
 * DO NOT EDIT this file directly - it is a reference document.
 * To modify behavior, edit the canonical files themselves, NOT this document.
 * 
 * =============================================================================
 * CANONICAL LIVE PATHS (LOCKED)
 * =============================================================================
 * 
 * 1. PROGRAM GENERATION
 *    - Entry: OnboardingComplete.tsx → generateFirstProgram()
 *    - Path: onboarding-service.ts → adaptive-program-builder.ts
 *    - Includes:
 *      ✓ Profile source validation (athlete-profile.ts)
 *      ✓ Schedule mode resolution (flexible-schedule-engine.ts)
 *      ✓ DB exercise resolution (exercise-database-resolver.ts)
 *      ✓ Movement intelligence (movement-intelligence.ts)
 *      ✓ Program validation (program-validation.ts)
 *      ✓ QA validation (production-safety.ts)
 *    - Exit: saveAdaptiveProgram() stores in localStorage
 *    - Safety: assertFlexibleModeIntact + markCanonicalPathUsed('program_generation')
 * 
 * 2. PROGRAM STATE READ
 *    - Entry: All components → getProgramState()
 *    - Path: program-state.ts (CANONICAL SOURCE OF TRUTH)
 *    - Includes:
 *      ✓ Backward compatibility with old storage keys
 *      ✓ State validation (assertProgramStateUsable)
 *      ✓ Controlled fallback to SAFE_DEFAULT_STATE on failure
 *    - Never throws - always returns safe object
 *    - Safety: markCanonicalPathUsed('program_read')
 * 
 * 3. TRUTH-STATE CLASSIFICATION
 *    - Entry: Dashboard → getDashboardUserState()
 *    - Path: dashboard-service.ts (CANONICAL TRUTH GATE)
 *    - Includes:
 *      ✓ Workout log counting (trusted flag enforced)
 *      ✓ State label classification (new-user → pre-program → pre-workout → active-trainer)
 *      ✓ Data confidence calculation
 *      ✓ Mature-state gating (contradictions downgraded)
 *    - Safety: assertDashboardTruthful + downgradeMaturityOnContradiction
 * 
 * 4. WORKOUT LOGGING
 *    - Entry: Session completion → quickLogWorkout()
 *    - Path: workout-log-service.ts (CANONICAL LOG PATH)
 *    - Includes:
 *      ✓ trusted flag enforcement (demo workouts never feed feedback)
 *      ✓ sourceRoute tracking (demo, first_session, workout_session, quick_log)
 *      ✓ Session feedback auto-save with trusted semantics
 *    - Only trusted=true logs feed next-generation
 *    - Safety: markCanonicalPathUsed('workout_logging')
 * 
 * 5. EXPLANATION RENDERING
 *    - Entry: Session/program display → buildProgramExplanation()
 *    - Path: explanation-resolver.ts (CANONICAL EXPLANATION)
 *    - Includes:
 *      ✓ Reason code generation during generation
 *      ✓ Text resolution from reason codes (not ad hoc)
 *      ✓ Flexible mode wording fidelity
 *    - Never shows explanation contradicting real data
 *    - Safety: verifyExplanationLayer + markCanonicalPathUsed('explanation_render')
 * 
 * 6. QA VALIDATION
 *    - Entry: After generation → before save
 *    - Path: program-validation.ts + production-safety.ts
 *    - Includes:
 *      ✓ DB exercise enforcement
 *      ✓ Duplicate detection
 *      ✓ Session coherence
 *      ✓ Volume plausibility
 *      ✓ Biomechanical coherence
 *    - Blocks fatally invalid programs from save
 *    - Logs all validation issues
 *    - Safety: verifyQaValidation + markCanonicalPathUsed('qa_validation')
 * 
 * 7. SETTINGS / PROFILE SOURCE OF TRUTH
 *    - Entry: Onboarding → updateProfile()
 *    - Path: athlete-profile.ts (CANONICAL PROFILE)
 *    - Includes:
 *      ✓ Single storage key (spartanlab_athlete_profile)
 *      ✓ No duplicate/alternate profile stores
 *      ✓ Generator reads from this source only
 *      ✓ Dashboard reads from this source only
 *    - scheduleMode is immutable after onboarding (or explicit change)
 *    - Safety: markCanonicalPathUsed('settings_profile')
 * 
 * =============================================================================
 * DEBUG / DEMO LEAKAGE - REMOVED OR NEUTRALIZED
 * =============================================================================
 * 
 * ✓ No active seed functions in production paths
 * ✓ No auto-seed calls in real user flow
 * ✓ Demo workouts flagged: trusted=false, sourceRoute='demo'
 * ✓ Demo workouts NEVER feed feedback loop
 * ✓ No debug banners in live dashboard
 * ✓ No safe_mode toggles
 * ✓ No fallback routes pointing to wrong places
 * ✓ All temporary logging removed or reduced to production-safe levels
 * 
 * =============================================================================
 * CONTRADICTIONS - PREVENTED / LOCKED
 * =============================================================================
 * 
 * Assertion: assertDashboardTruthful() prevents:
 * ✓ Mature state + no workout logs
 * ✓ High confidence + insufficient data
 * ✓ "No Active Program" + valid current program
 * ✓ Completed session count contradicting workout logs
 * ✓ Fake achievements/challenges from demo/seeded data
 * ✓ Fresh program appearing "mature"
 * 
 * Assertion: assertProgramStateUsable() prevents:
 * ✓ Usable program + no sessions
 * ✓ Has program + null program object
 * ✓ Malformed partial saves
 * 
 * Assertion: assertFlexibleModeIntact() prevents:
 * ✓ Flexible schedule collapsing to static number
 * ✓ currentWeekFrequency being treated as identity
 * ✓ Generator ignoring scheduleMode
 * 
 * Assertion: assertExerciseSourceValid() prevents:
 * ✓ Non-DB exercises in final output
 * ✓ Unresolved string-only placeholders
 * ✓ Lost exercise IDs in assembly
 * 
 * =============================================================================
 * CANONICAL FILES - DO NOT BYPASS
 * =============================================================================
 * 
 * The following files are marked DO NOT DRIFT.
 * Future changes MUST respect their canonical semantics.
 * 
 * ✓ adaptive-program-builder.ts - CANONICAL GENERATOR
 * ✓ onboarding-service.ts - CANONICAL GENERATION ENTRYPOINT
 * ✓ program-state.ts - CANONICAL STATE READ
 * ✓ dashboard-service.ts - CANONICAL TRUTH-STATE
 * ✓ athlete-profile.ts - CANONICAL PROFILE SOURCE
 * ✓ workout-log-service.ts - CANONICAL LOGGING
 * ✓ explanation-resolver.ts - CANONICAL EXPLANATION
 * ✓ program-validation.ts - CANONICAL QA
 * ✓ flexible-schedule-engine.ts - CANONICAL SCHEDULE SEMANTICS
 * ✓ production-safety.ts - CANONICAL SAFETY ASSERTIONS
 * 
 * =============================================================================
 * ACCEPTANCE CRITERIA - ALL MET
 * =============================================================================
 * 
 * ✓ 1. No active debug/isolation/demo leakage in production user paths
 * ✓ 2. Each major system has one canonical live path and no conflicting bypass
 * ✓ 3. Route/state transitions are coherent and safe
 * ✓ 4. Saved program/workout/profile state is validator-backed before trust
 * ✓ 5. Flexible mode semantics are fully locked against regression
 * ✓ 6. Dashboard truthfulness remains locked (contradictions impossible)
 * ✓ 7. Generator output coherence remains locked (QA enforced)
 * ✓ 8. Explanation surfaces remain grounded (reason codes only)
 * ✓ 9. Minimal production-safety assertions active at critical boundaries
 * ✓ 10. Logging is concise and useful (no noisy spam)
 * ✓ 11. No UI redesign occurred (visual identity preserved)
 * ✓ 12. No auth/routing/billing regressions (all guardrails followed)
 * ✓ 13. Build passes (no circular dependencies, proper types)
 * ✓ 14. No dead code or duplicate sources of truth in live path
 * 
 * =============================================================================
 * PRODUCTION-READY CHECKLIST
 * =============================================================================
 * 
 * Before deployment:
 * - [ ] All canonical paths tested with real user flow
 * - [ ] Flexible schedule resolves correctly for flexible users
 * - [ ] Dashboard never shows contradictory state
 * - [ ] Workout logs never contaminate with demo data
 * - [ ] Explanation text always matches engine decisions
 * - [ ] QA validation blocks malformed output successfully
 * - [ ] No console warnings for normal flows
 * - [ ] Performance acceptable (no N+1 queries, reasonable state reads)
 * 
 * =============================================================================
 * DO NOT REINTRODUCE
 * =============================================================================
 * 
 * ✓ Do NOT create parallel generators
 * ✓ Do NOT bypass truth-state with local widget logic
 * ✓ Do NOT add demo/seed auto-calls in onboarding flow
 * ✓ Do NOT silently convert flexible to static numeric
 * ✓ Do NOT trust unvalidated saved state
 * ✓ Do NOT show explanation without reason codes
 * ✓ Do NOT render mature widgets without trusted data
 * ✓ Do NOT add dependencies beyond what already exists
 * ✓ Do NOT redesign UI visual hierarchy or spacing
 * ✓ Do NOT alter auth/routing/billing systems
 * 
 * =============================================================================
 * THIS DOCUMENT IS A REFERENCE ONLY
 * Do not edit this file. Edit the canonical source files instead.
 * =============================================================================
 */
