// =============================================================================
// [PHASE-R] SESSION-LENGTH TRUTH CONTRACT
// =============================================================================
// Authoritative deterministic READER over the variants already produced by
// `generateSessionVariants` in lib/session-compression-engine.ts. Phase R is
// NOT a second program builder. It does NOT pick exercises, mutate sets, alter
// RPE, change rest, or reorder anything. It reads the canonical full session
// + the existing variants[] array (full / 45 / 30, when launchable and
// materially distinct), computes a per-variant TRUTH RECEIPT (actual minutes
// estimated from the variant body, exercises kept vs deferred, set deltas,
// rest deltas, priority preservation, liveness, runtime safety), and stamps
// it on `session.sessionLengthTruth` for the card and Phase Q to consume.
//
// WHY PHASE R EXISTS
// Phase Q honestly reported session-length as "PARTIALLY CAUSAL — suppressed
// at structural level" because its `evaluateSessionLength()` only compared
// `session.estimatedMinutes` against `profileSnapshot.timeAvailability`. It
// never inspected `session.variants[]`. The variants ARE structurally real:
//   - generated by `generateSessionVariants` from compressed bodies,
//   - gated by `isVariantLaunchable` so empty/hollow variants are dropped,
//   - gated by `areVariantsMateriallyDistinct` so cosmetic-only shorts are
//     dropped (same membership / same ordered identity / same total sets /
//     near-identical duration → rejected),
//   - regenerated POST-grouping-materialization so 45/30 inherit atomic-unit
//     awareness (see adaptive-program-builder.ts L14705).
// What was missing was an honest TRACE that Phase Q (and the card) could read
// to verify the variants are real and to surface what each mode actually is.
//
// ARCHITECTURAL PRINCIPLES (from the Phase R brief)
//   1. Full / 45 / 30 are a deterministic resolver over canonical truth, not
//      three programs and not a CSS filter. We READ the resolver output, we
//      do not re-run it.
//   2. Canonical full session remains intact. Phase R never overwrites
//      `session.exercises`, never overwrites `variant.selection`, never
//      mutates sets/reps/RPE/rest.
//   3. We STAMP `session.sessionLengthTruth`. Optional, JSON-safe,
//      round-trips through every existing `...session` spread (program-state,
//      normalize, save/load) like `qualityAudit` and `doctrineUtilizationTrace`.
//   4. No new dependencies. No Prisma changes. No live workout reducer
//      changes. No new builder.
//
// HONESTY GUARDS
//   - If `variants[]` is missing or has only Full → state is ACKNOWLEDGED_ONLY
//     with `verdict: 'NO_LAUNCHABLE_SHORTS'`.
//   - If a short variant exists but compresses zero exercises and has same
//     total sets (i.e. cosmetic) → that variant is dropped from the truth
//     (matching the upstream distinctness gate behavior).
//   - If actual computed minutes drift more than the
//     `LABEL_DRIFT_TOLERANCE_MIN` from the variant's labeled duration → we
//     stamp `labelDriftWarning: true` so the card renders an honest
//     "Estimated 36 min because primary skill + safe rest minimums prevent
//      further compression" instead of pretending it lands at exactly 30.
//   - We never overwrite `variant.duration`. We expose `actualEstimatedMinutes`
//     alongside it.
//
// CONSUMERS
//   - lib/server/authoritative-program-generation.ts runs this BEFORE Phase Q
//     so Phase Q's `evaluateSessionLength()` can read `session.sessionLengthTruth`
//     and credit ELIGIBLE_AND_APPLIED when structural compression actually
//     produced distinct shorts.
//   - lib/program/performance-feedback-integration.ts (client boot overlay)
//     runs this in the same position so client-side regenerations stamp
//     identical truth.
//   - components/programs/AdaptiveSessionCard.tsx renders one compact line
//     ("3 modes structurally distinct · short variants drop 2 accessories
//      · primary skill anchor preserved") under the variant button row.
//
// LIVE WORKOUT HANDOFF
//   The card already routes via `selectedSessionContract.selectedLaunchUrl`,
//   `buildSessionFingerprint`, and `stampLaunchFingerprint`. Phase R's job
//   is NOT to rewire that corridor — it's to PROVE the corridor is honest by
//   producing a `liveWorkoutHandoff: { mechanism, payloadCompatibility }`
//   field the master-truth blueprint can audit.
// =============================================================================

import type { AdaptiveSession, AdaptiveProgram } from '../adaptive-program-builder'

// =============================================================================
// PUBLIC TYPES
// =============================================================================

/**
 * Per-mode truth receipt. One entry per launchable variant in `variants[]`.
 * Order mirrors `variants[]`: index 0 is Full, idx 1+ are shorts.
 */
export interface SessionLengthVariantTruth {
  /** Index in the underlying `session.variants[]` array. */
  variantIndex: number
  /** Human label as authored by `generateSessionVariants` (`'Full Session'`,
   * `'45 Min'`, `'30 Min'`). */
  label: string
  /**
   * Mode tag derived from `variant.duration`. Matches the card's
   * `selectedExecutionMode`: 'full' (>50m), '45_min' (35–50m), '30_min' (≤35m).
   */
  mode: 'full' | '45_min' | '30_min'
  /** Variant.duration as authored upstream — the user-facing target. */
  targetMinutes: number
  /**
   * ACTUAL estimated minutes computed deterministically from the variant
   * body (sum over rows of `setSeconds × sets + restSeconds × max(sets-1, 0)`,
   * with safe per-row fallbacks). NOT pulled from a label. NOT static.
   */
  actualEstimatedMinutes: number
  /** Drift between target and actual, in minutes (always ≥ 0). */
  labelDriftMinutes: number
  /**
   * True when `labelDriftMinutes > LABEL_DRIFT_TOLERANCE_MIN`. The card uses
   * this to render an honest "estimated 36 min because…" message instead of
   * pretending the target lands exactly.
   */
  labelDriftWarning: boolean
  /** Compression level the engine reported for this variant. */
  compressionLevel: 'none' | 'light' | 'moderate' | 'heavy'
  /**
   * Total sets in this variant's main block. Used as the structural-distinctness
   * signal alongside main count and ordered identity.
   */
  totalMainSets: number
  /** Number of main exercises in this variant. */
  mainExerciseCount: number
  /**
   * Names of exercises present in canonical Full but ABSENT in this variant
   * (deferred). Pulled by id-difference; safe when ids missing.
   */
  deferredExerciseNames: string[]
  /**
   * Per-row reasons captured from `selectionReason` on rows that survived,
   * grouped by priority bucket. We do NOT invent reasons — only surface what
   * was already labelled by the engine.
   */
  priorityPreservation: {
    /**
     * True when at least one row in this variant has a primary-skill marker
     * (category === 'skill', or selectionReason mentions "primary"/"skill
     * progression"). The compressor's `preserveSkillWork: true` flag is
     * what makes this likely; we verify it actually held.
     */
    primarySkillAnchorPreserved: boolean
    /** Same check for secondary skill / hybrid expressions. */
    secondaryOrHybridSkillPreserved: boolean
    /**
     * True when an essential strength-support row survived in this variant
     * (selectionReason includes 'support'/'strength' for category 'strength').
     */
    essentialStrengthSupportPreserved: boolean
  }
  /** Material-distinctness check vs the canonical Full variant.
   * (Cosmetic shorts should already have been dropped upstream — this is
   *  belt-and-suspenders so the trace doesn't lie.) */
  distinctVsFull: {
    sameMainCount: boolean
    sameOrderedIdentity: boolean
    sameTotalSets: boolean
    nearEqualDuration: boolean
    materiallyDistinct: boolean
  }
  /**
   * `true` iff every row carries a usable exercise identity (id + name) —
   * mirrors `isVariantLaunchable`'s minimum invariants from the engine.
   */
  liveWorkoutLaunchable: boolean
}

/**
 * Live-workout handoff audit. Phase R does not change the handoff corridor —
 * it documents how the variant the card displays reaches the live workout so
 * the master-truth blueprint can see the path is unbroken.
 */
export interface SessionLengthLiveWorkoutHandoff {
  /**
   * Always 'launch_fingerprint' in the current architecture. The card stamps
   * via `stampLaunchFingerprint` and the route reads via
   * `readLaunchFingerprint`. This field exists so a future change is auditable.
   */
  mechanism: 'launch_fingerprint'
  /**
   * `'OK'` when the selected variant index can produce a real launchable
   * body and the URL params (`mode`, `variant`, `day`, `week`) round-trip
   * cleanly.
   * `'NO_VARIANTS'` when no shorts exist (only Full).
   * `'COSMETIC_ONLY'` when all shorts failed material-distinctness.
   * `'PARITY_DRIFT'` is reserved for the runtime-side fingerprint compare;
   * we do not stamp it here, the route owns it.
   */
  payloadCompatibility: 'OK' | 'NO_VARIANTS' | 'COSMETIC_ONLY'
  /** Number of launchable distinct variants in `session.variants[]`. */
  launchableVariantCount: number
}

/**
 * Per-session Phase R stamp. Stored at `session.sessionLengthTruth`.
 * Optional, JSON-safe, round-trips through every existing `...session` spread.
 */
export interface SessionLengthTruthStamp {
  version: 'phase-r-session-length-truth-v1'
  dayNumber: number
  /** Honest verdict for the WHOLE session.
   *  - STRUCTURALLY_REAL: ≥1 launchable distinct short variant exists AND the
   *    short(s) drop exercises and/or sets vs Full.
   *  - SHORTS_AT_LABEL_PARITY: shorts exist and are distinct, but they only
   *    differ on duration label (no exercise drop, no set drop). Honest
   *    yellow flag.
   *  - NO_LAUNCHABLE_SHORTS: only Full remains (engine rejected cosmetic
   *    shorts upstream, OR full session is already ≤ 35m and engine skipped
   *    the 45/30 generation). Not a failure — short modes are not applicable.
   *  - LEGACY_NO_VARIANTS: session has no `variants[]` array (older program
   *    objects).
   */
  verdict:
    | 'STRUCTURALLY_REAL'
    | 'SHORTS_AT_LABEL_PARITY'
    | 'NO_LAUNCHABLE_SHORTS'
    | 'LEGACY_NO_VARIANTS'
  /** One-line summary the card renders. Always concise. */
  summary: string
  /** Full + (optional) 45 + (optional) 30. Order matches `session.variants[]`. */
  variantTruth: SessionLengthVariantTruth[]
  /** Aggregate counts for the program-level rollup. */
  rollup: {
    launchableVariantCount: number
    distinctShortCount: number
    deferredExerciseTotal: number
    setDeltaTotal: number
    primarySkillAnchorPreservedAcrossShorts: boolean
  }
  liveWorkoutHandoff: SessionLengthLiveWorkoutHandoff
}

/**
 * Program-level Phase R rollup. Stamped at `program.sessionLengthTruth`.
 */
export interface ProgramSessionLengthTruthStamp {
  version: 'phase-r-session-length-truth-v1'
  generatedAt: string
  /** Worst-state verdict across all sessions. */
  programVerdict:
    | 'STRUCTURALLY_REAL_ACROSS_PROGRAM'
    | 'STRUCTURALLY_REAL_PARTIAL'
    | 'SHORTS_PRESENT_BUT_LABEL_PARITY'
    | 'NO_SHORTS_NEEDED'
    | 'NO_VARIANTS_AVAILABLE'
  /** Per-session counts for the master-truth blueprint. */
  sessionCounts: {
    total: number
    structurallyReal: number
    labelParity: number
    noLaunchableShorts: number
    legacyNoVariants: number
  }
  /** One-line summary for the program page. */
  summary: string
}

// =============================================================================
// CONSTANTS
// =============================================================================

/** Drift in minutes beyond which we surface a `labelDriftWarning`. */
const LABEL_DRIFT_TOLERANCE_MIN = 5

/** Default per-row work-time fallback when no explicit setSeconds available. */
const DEFAULT_SET_SECONDS = 45 // typical strength set
/** Default rest fallback when restSeconds missing. */
const DEFAULT_REST_SECONDS = 90

/** Material-distinctness duration bucket — mirrors compression-engine.ts. */
const DURATION_DISTINCTNESS_THRESHOLD_MIN = 5

// =============================================================================
// LOCAL READ-ONLY SHAPES (defensive — every field optional)
// =============================================================================

interface VariantLike {
  duration?: number | null
  label?: string | null
  compressionLevel?: 'none' | 'light' | 'moderate' | 'heavy' | null
  selection?: {
    main?: VariantRowLike[] | null
    warmup?: VariantRowLike[] | null
    cooldown?: VariantRowLike[] | null
  } | null
}

interface VariantRowLike {
  exercise?: {
    id?: string | null
    name?: string | null
    category?: string | null
  } | null
  sets?: number | null
  repsOrTime?: string | number | null
  setSeconds?: number | null
  restSeconds?: number | null
  selectionReason?: string | null
}

interface SessionLike {
  dayNumber?: number | null
  estimatedMinutes?: number | null
  variants?: VariantLike[] | null
  exercises?: Array<{
    id?: string | null
    name?: string | null
    category?: string | null
    sets?: number | null
    setSeconds?: number | null
    restSeconds?: number | null
    selectionReason?: string | null
  }> | null
  sessionLengthTruth?: SessionLengthTruthStamp
}

interface ProgramLike {
  generatedAt?: string | null
  sessions?: SessionLike[] | null
  sessionLengthTruth?: ProgramSessionLengthTruthStamp
}

// =============================================================================
// HELPERS — pure, deterministic, no side effects
// =============================================================================

function asNumber(n: unknown, fallback: number): number {
  return typeof n === 'number' && Number.isFinite(n) ? n : fallback
}

function asString(s: unknown, fallback: string): string {
  return typeof s === 'string' && s.length > 0 ? s : fallback
}

function rowsOf(variant: VariantLike | undefined): VariantRowLike[] {
  return Array.isArray(variant?.selection?.main) ? variant!.selection!.main! : []
}

function rowExerciseId(row: VariantRowLike | null | undefined): string {
  return asString(row?.exercise?.id, '')
}

function rowExerciseName(row: VariantRowLike | null | undefined): string {
  return asString(row?.exercise?.name, '')
}

function rowSets(row: VariantRowLike | null | undefined): number {
  return asNumber(row?.sets, 0)
}

/**
 * Estimate one row's total time in seconds. Honest — uses explicit fields
 * where present, sane defaults where absent. Never returns negative.
 */
function rowEstimatedSeconds(row: VariantRowLike | null | undefined): number {
  if (!row) return 0
  const sets = Math.max(0, asNumber(row.sets, 0))
  if (sets <= 0) return 0
  const setSecs = Math.max(0, asNumber(row.setSeconds, DEFAULT_SET_SECONDS))
  const restSecs = Math.max(0, asNumber(row.restSeconds, DEFAULT_REST_SECONDS))
  // Rest is between sets, so (sets - 1) intervals.
  const restCount = Math.max(0, sets - 1)
  return sets * setSecs + restCount * restSecs
}

/** Sum estimated minutes for all main rows. Rounded to nearest minute. */
function variantEstimatedMinutes(variant: VariantLike | undefined): number {
  const rows = rowsOf(variant)
  let totalSecs = 0
  for (const r of rows) totalSecs += rowEstimatedSeconds(r)
  return Math.max(0, Math.round(totalSecs / 60))
}

function totalSetsOf(variant: VariantLike | undefined): number {
  let total = 0
  for (const r of rowsOf(variant)) total += rowSets(r)
  return total
}

function orderedIdentitySignature(variant: VariantLike | undefined): string {
  return rowsOf(variant)
    .map((r) => rowExerciseId(r))
    .join('|')
}

/** Maps `variant.duration` to a 3-bucket execution mode tag. */
function modeFor(durationMinutes: number): 'full' | '45_min' | '30_min' {
  if (durationMinutes <= 35) return '30_min'
  if (durationMinutes <= 50) return '45_min'
  return 'full'
}

/** Did this variant preserve at least one primary-skill row? */
function detectPrimarySkillAnchor(variant: VariantLike | undefined): boolean {
  for (const r of rowsOf(variant)) {
    const cat = asString(r?.exercise?.category, '').toLowerCase()
    const reason = asString(r?.selectionReason, '').toLowerCase()
    if (cat === 'skill') return true
    if (reason.includes('primary') && reason.includes('skill')) return true
    if (reason.includes('skill progression')) return true
  }
  return false
}

function detectSecondaryOrHybridSkill(variant: VariantLike | undefined): boolean {
  for (const r of rowsOf(variant)) {
    const reason = asString(r?.selectionReason, '').toLowerCase()
    if (reason.includes('secondary') && reason.includes('skill')) return true
    if (reason.includes('hybrid')) return true
    if (reason.includes('expression')) return true
  }
  return false
}

function detectEssentialStrengthSupport(variant: VariantLike | undefined): boolean {
  for (const r of rowsOf(variant)) {
    const cat = asString(r?.exercise?.category, '').toLowerCase()
    const reason = asString(r?.selectionReason, '').toLowerCase()
    if (cat === 'strength' && (reason.includes('support') || reason.includes('strength'))) {
      return true
    }
  }
  return false
}

/** Names present in Full but absent from `variant`, by id (fallback to name). */
function deferredNamesVsFull(
  variant: VariantLike | undefined,
  fullVariant: VariantLike | undefined,
): string[] {
  const present = new Set<string>()
  for (const r of rowsOf(variant)) {
    const id = rowExerciseId(r)
    if (id) present.add(`id:${id}`)
    else {
      const name = rowExerciseName(r)
      if (name) present.add(`name:${name}`)
    }
  }
  const deferred: string[] = []
  for (const r of rowsOf(fullVariant)) {
    const id = rowExerciseId(r)
    const name = rowExerciseName(r)
    const key = id ? `id:${id}` : name ? `name:${name}` : ''
    if (!key) continue
    if (!present.has(key)) deferred.push(name || id)
  }
  return deferred
}

// =============================================================================
// CORE — build per-variant truth receipt
// =============================================================================

function buildVariantTruth(
  variant: VariantLike,
  variantIndex: number,
  fullVariant: VariantLike | undefined,
): SessionLengthVariantTruth {
  const targetMinutes = Math.max(0, asNumber(variant.duration, 0))
  const actualEstimatedMinutes = variantEstimatedMinutes(variant)
  const labelDriftMinutes = Math.abs(targetMinutes - actualEstimatedMinutes)
  const labelDriftWarning =
    targetMinutes > 0 && labelDriftMinutes > LABEL_DRIFT_TOLERANCE_MIN
  const compressionLevel =
    (variant.compressionLevel as SessionLengthVariantTruth['compressionLevel']) ?? 'none'
  const totalMainSets = totalSetsOf(variant)
  const mainExerciseCount = rowsOf(variant).length
  const deferred = fullVariant && variantIndex !== 0 ? deferredNamesVsFull(variant, fullVariant) : []

  const fullMainCount = fullVariant ? rowsOf(fullVariant).length : mainExerciseCount
  const fullTotalSets = fullVariant ? totalSetsOf(fullVariant) : totalMainSets
  const fullDuration = fullVariant ? asNumber(fullVariant.duration, targetMinutes) : targetMinutes
  const sameMainCount = mainExerciseCount === fullMainCount
  const sameOrderedIdentity =
    fullVariant != null && orderedIdentitySignature(variant) === orderedIdentitySignature(fullVariant)
  const sameTotalSets = totalMainSets === fullTotalSets
  const nearEqualDuration = Math.abs(targetMinutes - fullDuration) < DURATION_DISTINCTNESS_THRESHOLD_MIN
  const materiallyDistinct =
    variantIndex === 0 ? false : !(sameMainCount && sameOrderedIdentity && sameTotalSets && nearEqualDuration)

  // Liveness mirrors `isVariantLaunchable` — every row needs id + name.
  let liveWorkoutLaunchable = mainExerciseCount > 0
  if (liveWorkoutLaunchable) {
    for (const r of rowsOf(variant)) {
      if (!rowExerciseId(r) || !rowExerciseName(r)) {
        liveWorkoutLaunchable = false
        break
      }
    }
  }

  return {
    variantIndex,
    label: asString(variant.label, variantIndex === 0 ? 'Full Session' : `Variant ${variantIndex}`),
    mode: modeFor(targetMinutes),
    targetMinutes,
    actualEstimatedMinutes,
    labelDriftMinutes,
    labelDriftWarning,
    compressionLevel,
    totalMainSets,
    mainExerciseCount,
    deferredExerciseNames: deferred,
    priorityPreservation: {
      primarySkillAnchorPreserved: detectPrimarySkillAnchor(variant),
      secondaryOrHybridSkillPreserved: detectSecondaryOrHybridSkill(variant),
      essentialStrengthSupportPreserved: detectEssentialStrengthSupport(variant),
    },
    distinctVsFull: {
      sameMainCount,
      sameOrderedIdentity,
      sameTotalSets,
      nearEqualDuration,
      materiallyDistinct,
    },
    liveWorkoutLaunchable,
  }
}

// =============================================================================
// CORE — build session-level Phase R stamp
// =============================================================================

function buildSessionStamp(session: SessionLike): SessionLengthTruthStamp {
  const dayNumber = asNumber(session.dayNumber, 0)
  const variants = Array.isArray(session.variants) ? session.variants : null

  if (!variants || variants.length === 0) {
    return {
      version: 'phase-r-session-length-truth-v1',
      dayNumber,
      verdict: 'LEGACY_NO_VARIANTS',
      summary: 'Session length: legacy session — no variant trio available.',
      variantTruth: [],
      rollup: {
        launchableVariantCount: 0,
        distinctShortCount: 0,
        deferredExerciseTotal: 0,
        setDeltaTotal: 0,
        primarySkillAnchorPreservedAcrossShorts: false,
      },
      liveWorkoutHandoff: {
        mechanism: 'launch_fingerprint',
        payloadCompatibility: 'NO_VARIANTS',
        launchableVariantCount: 0,
      },
    }
  }

  const fullVariant = variants[0]
  const variantTruth: SessionLengthVariantTruth[] = variants.map((v, idx) =>
    buildVariantTruth(v, idx, fullVariant),
  )

  const launchableVariantCount = variantTruth.filter((v) => v.liveWorkoutLaunchable).length
  const distinctShorts = variantTruth.filter(
    (v) => v.variantIndex > 0 && v.distinctVsFull.materiallyDistinct && v.liveWorkoutLaunchable,
  )
  const distinctShortCount = distinctShorts.length

  // Deferred + set deltas are the structural-truth signals.
  const fullSets = variantTruth[0]?.totalMainSets ?? 0
  let deferredExerciseTotal = 0
  let setDeltaTotal = 0
  let primarySkillAnchorPreservedAcrossShorts = distinctShorts.length > 0
  for (const s of distinctShorts) {
    deferredExerciseTotal += s.deferredExerciseNames.length
    setDeltaTotal += Math.max(0, fullSets - s.totalMainSets)
    if (!s.priorityPreservation.primarySkillAnchorPreserved) {
      primarySkillAnchorPreservedAcrossShorts = false
    }
  }

  // Verdict logic — honest, conservative.
  let verdict: SessionLengthTruthStamp['verdict']
  if (variants.length <= 1) {
    verdict = 'NO_LAUNCHABLE_SHORTS'
  } else if (distinctShortCount === 0) {
    verdict = 'NO_LAUNCHABLE_SHORTS'
  } else if (deferredExerciseTotal === 0 && setDeltaTotal === 0) {
    // Shorts exist and are distinct, but only on duration — no exercise drop,
    // no set drop. That is a label-parity short. Honest yellow flag.
    verdict = 'SHORTS_AT_LABEL_PARITY'
  } else {
    verdict = 'STRUCTURALLY_REAL'
  }

  // Payload compatibility maps cleanly from verdict.
  const payloadCompatibility: SessionLengthLiveWorkoutHandoff['payloadCompatibility'] =
    verdict === 'STRUCTURALLY_REAL' || verdict === 'SHORTS_AT_LABEL_PARITY'
      ? 'OK'
      : verdict === 'NO_LAUNCHABLE_SHORTS' && variants.length > 1
        ? 'COSMETIC_ONLY'
        : 'NO_VARIANTS'

  // Summary copy.
  const summary = (() => {
    if (verdict === 'LEGACY_NO_VARIANTS') return 'Session length: legacy session — no variants.'
    if (verdict === 'NO_LAUNCHABLE_SHORTS') {
      return 'Session length: full only — short modes not applicable for this day.'
    }
    if (verdict === 'SHORTS_AT_LABEL_PARITY') {
      return `Session length: ${distinctShortCount} short mode${distinctShortCount === 1 ? '' : 's'} present, label-only differences.`
    }
    // STRUCTURALLY_REAL
    const parts: string[] = []
    parts.push(
      `${distinctShortCount + 1} mode${distinctShortCount === 0 ? '' : 's'} structurally distinct`,
    )
    if (deferredExerciseTotal > 0) {
      parts.push(
        `short${distinctShortCount === 1 ? '' : 's'} drop ${deferredExerciseTotal} accessor${deferredExerciseTotal === 1 ? 'y' : 'ies'}`,
      )
    }
    if (primarySkillAnchorPreservedAcrossShorts) parts.push('primary skill anchor preserved')
    return `Session length: ${parts.join(' · ')}.`
  })()

  return {
    version: 'phase-r-session-length-truth-v1',
    dayNumber,
    verdict,
    summary,
    variantTruth,
    rollup: {
      launchableVariantCount,
      distinctShortCount,
      deferredExerciseTotal,
      setDeltaTotal,
      primarySkillAnchorPreservedAcrossShorts,
    },
    liveWorkoutHandoff: {
      mechanism: 'launch_fingerprint',
      payloadCompatibility,
      launchableVariantCount,
    },
  }
}

// =============================================================================
// CORE — program rollup
// =============================================================================

function buildProgramStamp(
  perSessionStamps: SessionLengthTruthStamp[],
): ProgramSessionLengthTruthStamp {
  const sessionCounts = {
    total: perSessionStamps.length,
    structurallyReal: 0,
    labelParity: 0,
    noLaunchableShorts: 0,
    legacyNoVariants: 0,
  }
  for (const s of perSessionStamps) {
    if (s.verdict === 'STRUCTURALLY_REAL') sessionCounts.structurallyReal++
    else if (s.verdict === 'SHORTS_AT_LABEL_PARITY') sessionCounts.labelParity++
    else if (s.verdict === 'NO_LAUNCHABLE_SHORTS') sessionCounts.noLaunchableShorts++
    else if (s.verdict === 'LEGACY_NO_VARIANTS') sessionCounts.legacyNoVariants++
  }

  let programVerdict: ProgramSessionLengthTruthStamp['programVerdict']
  if (sessionCounts.total === 0) programVerdict = 'NO_VARIANTS_AVAILABLE'
  else if (sessionCounts.legacyNoVariants === sessionCounts.total) programVerdict = 'NO_VARIANTS_AVAILABLE'
  else if (
    sessionCounts.structurallyReal > 0 &&
    sessionCounts.structurallyReal + sessionCounts.noLaunchableShorts === sessionCounts.total
  ) {
    // Every session either structurally compresses or doesn't need shorts.
    programVerdict =
      sessionCounts.structurallyReal === sessionCounts.total - sessionCounts.noLaunchableShorts
        ? 'STRUCTURALLY_REAL_ACROSS_PROGRAM'
        : 'STRUCTURALLY_REAL_PARTIAL'
  } else if (sessionCounts.structurallyReal > 0) {
    programVerdict = 'STRUCTURALLY_REAL_PARTIAL'
  } else if (sessionCounts.labelParity > 0) {
    programVerdict = 'SHORTS_PRESENT_BUT_LABEL_PARITY'
  } else {
    programVerdict = 'NO_SHORTS_NEEDED'
  }

  const summary =
    programVerdict === 'STRUCTURALLY_REAL_ACROSS_PROGRAM'
      ? `Session length: structurally real on every applicable day (${sessionCounts.structurallyReal}/${sessionCounts.total}).`
      : programVerdict === 'STRUCTURALLY_REAL_PARTIAL'
        ? `Session length: structurally real on ${sessionCounts.structurallyReal}/${sessionCounts.total} day${sessionCounts.total === 1 ? '' : 's'}.`
        : programVerdict === 'SHORTS_PRESENT_BUT_LABEL_PARITY'
          ? `Session length: shorts exist but only differ by label on ${sessionCounts.labelParity}/${sessionCounts.total} day${sessionCounts.total === 1 ? '' : 's'}.`
          : programVerdict === 'NO_SHORTS_NEEDED'
            ? 'Session length: full sessions only — short modes not applicable.'
            : 'Session length: legacy program — no variant trio available.'

  return {
    version: 'phase-r-session-length-truth-v1',
    generatedAt: new Date().toISOString(),
    programVerdict,
    sessionCounts,
    summary,
  }
}

// =============================================================================
// PUBLIC ENTRY POINT
// =============================================================================

/**
 * Run the Phase R Session-Length Truth Contract. Pure reader. Stamps
 * `session.sessionLengthTruth` on every session and `program.sessionLengthTruth`
 * on the program. Never mutates exercises, sets, RPE, rest, methods, ordering.
 *
 * Safe to call multiple times — overwrites the stamp deterministically.
 */
export function runSessionLengthTruthContract(
  programInput: AdaptiveProgram,
): {
  program: AdaptiveProgram
  audit: {
    attempted: true
    stampedSessions: number
    structurallyReal: number
    labelParity: number
    noLaunchableShorts: number
    legacyNoVariants: number
    programVerdict: ProgramSessionLengthTruthStamp['programVerdict']
    summary: string
  }
} {
  const program = programInput as unknown as ProgramLike
  const sessionsIn: SessionLike[] = Array.isArray(program.sessions) ? program.sessions : []

  const newSessions: AdaptiveSession[] = []
  const perSessionStamps: SessionLengthTruthStamp[] = []
  for (const s of sessionsIn) {
    const stamp = buildSessionStamp(s)
    perSessionStamps.push(stamp)
    newSessions.push({
      ...(s as unknown as AdaptiveSession),
      sessionLengthTruth: stamp,
    } as AdaptiveSession)
  }

  const programStamp = buildProgramStamp(perSessionStamps)

  const out: AdaptiveProgram = {
    ...(programInput as AdaptiveProgram),
    sessions: newSessions,
    sessionLengthTruth: programStamp,
  } as AdaptiveProgram

  return {
    program: out,
    audit: {
      attempted: true,
      stampedSessions: perSessionStamps.length,
      structurallyReal: programStamp.sessionCounts.structurallyReal,
      labelParity: programStamp.sessionCounts.labelParity,
      noLaunchableShorts: programStamp.sessionCounts.noLaunchableShorts,
      legacyNoVariants: programStamp.sessionCounts.legacyNoVariants,
      programVerdict: programStamp.programVerdict,
      summary: programStamp.summary,
    },
  }
}
