// Adaptive Exercise Pool
// Curated high-value exercise library for calisthenics athletes
// Each exercise includes transfer ratings, fatigue cost, and equipment requirements

export type EquipmentType = 'pull_bar' | 'dip_bars' | 'rings' | 'parallettes' | 'bands' | 'floor' | 'wall'
export type MovementPattern = 'horizontal_push' | 'vertical_push' | 'horizontal_pull' | 'vertical_pull' | 'core' | 'compression' | 'transition' | 'skill' | 'mobility'
export type ExerciseCategory = 'skill' | 'strength' | 'accessory' | 'core' | 'warmup' | 'cooldown' | 'flexibility'

// Extended category for movement classification (push/pull/compression)
export type MovementCategory = 'push' | 'pull' | 'compression' | 'core' | 'flexibility' | 'accessory' | 'warmup' | 'cooldown'

// Difficulty levels for progression
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced' | 'elite'

export interface MethodCompatibility {
  straightSets?: boolean
  superset?: boolean
  density?: boolean
  dropSet?: boolean
  ladder?: boolean
  emom?: boolean
  clusterSet?: boolean
  restPause?: boolean
}

export type FailureRisk = 'low' | 'moderate' | 'high'

export interface Exercise {
  id: string
  name: string
  category: ExerciseCategory
  movementPattern: MovementPattern
  primaryMuscles: string[]
  equipment: EquipmentType[]
  neuralDemand: 1 | 2 | 3 | 4 | 5 // 5 = highest skill/neural requirement
  fatigueCost: 1 | 2 | 3 | 4 | 5 // 5 = most fatiguing
  transferTo: string[] // skill IDs this helps
  defaultSets: number
  defaultRepsOrTime: string
  notes?: string
  alternatives?: string[] // exercise IDs that can substitute
  methodCompatibility?: MethodCompatibility // training methods this exercise works with
  failureRisk?: FailureRisk // Risk level when training near failure
  dropSetProgression?: string[] // Easier variations for mechanical drop sets
  supportsBandAssistance?: boolean // Whether this exercise can use band assistance
  // New fields for enhanced exercise library
  difficultyLevel?: DifficultyLevel // beginner/intermediate/advanced/elite
  movementCategory?: MovementCategory // push/pull/compression classification
  supportsRPE?: boolean // Whether RPE tracking is meaningful for this exercise
  isIsometric?: boolean // Whether this is a hold/static exercise
  targetTimeUnderTension?: string // For isometric exercises
  // Progression system fields
  progressionUp?: string // ID of the harder progression
  progressionDown?: string // ID of the easier regression
  substitutionOptions?: string[] // Exercise IDs that can substitute this movement
  progressionLadder?: string // ID of the progression ladder this belongs to
}

// =============================================================================
// SKILL EXERCISES - Highest neural demand, placed first in sessions
// =============================================================================
export const SKILL_EXERCISES: Exercise[] = [
  // ===== PLANCHE PROGRESSIONS =====
  {
    id: 'planche_lean',
    name: 'Planche Leans',
    category: 'skill',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'core'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 4,
    fatigueCost: 2,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '15-20s',
    notes: 'Focus on lean angle progression',
    methodCompatibility: { straightSets: true, clusterSet: true },
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'tuck_planche',
    progressionLadder: 'planche',
    substitutionOptions: ['pppu', 'ring_push_up'],
  },
  {
    id: 'tuck_planche',
    name: 'Tuck Planche Hold',
    category: 'skill',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'core'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 5,
    fatigueCost: 3,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '8-12s',
    alternatives: ['adv_tuck_planche'],
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'adv_tuck_planche',
    progressionDown: 'planche_lean',
    progressionLadder: 'planche',
    substitutionOptions: ['banded_planche_hold', 'planche_lean'],
  },
  {
    id: 'adv_tuck_planche',
    name: 'Adv Tuck Planche Hold',
    category: 'skill',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'core'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '6-10s',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'straddle_planche',
    progressionDown: 'tuck_planche',
    progressionLadder: 'planche',
    substitutionOptions: ['tuck_planche', 'banded_planche_hold'],
  },
  {
    id: 'straddle_planche',
    name: 'Straddle Planche Hold',
    category: 'skill',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'core'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 5,
    fatigueCost: 5,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '3-6s',
    supportsBandAssistance: true,
    difficultyLevel: 'elite',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    progressionDown: 'adv_tuck_planche',
    progressionLadder: 'planche',
    substitutionOptions: ['adv_tuck_planche'],
  },
  {
    id: 'banded_planche_hold',
    name: 'Banded Planche Hold',
    category: 'skill',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'core'],
    equipment: ['floor', 'parallettes', 'bands'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '10-15s',
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Band-assisted planche practice',
  },
  // ===== FRONT LEVER PROGRESSIONS =====
  {
    id: 'tuck_fl',
    name: 'Tuck Front Lever Hold',
    category: 'skill',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '10-15s',
    alternatives: ['adv_tuck_fl'],
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'adv_tuck_fl',
    progressionLadder: 'front_lever',
    substitutionOptions: ['banded_fl_hold', 'tuck_front_lever_pull'],
  },
  {
    id: 'adv_tuck_fl',
    name: 'Adv Tuck Front Lever Hold',
    category: 'skill',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '8-12s',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'one_leg_fl',
    progressionDown: 'tuck_fl',
    progressionLadder: 'front_lever',
    substitutionOptions: ['tuck_fl', 'banded_fl_hold'],
  },
  {
    id: 'one_leg_fl',
    name: 'One Leg Front Lever Hold',
    category: 'skill',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '6-10s',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    isIsometric: true,
    progressionUp: 'straddle_fl',
    progressionDown: 'adv_tuck_fl',
    progressionLadder: 'front_lever',
    substitutionOptions: ['adv_tuck_fl'],
  },
  {
    id: 'straddle_fl',
    name: 'Straddle Front Lever Hold',
    category: 'skill',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 5,
    fatigueCost: 5,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '3-6s',
    supportsBandAssistance: true,
    difficultyLevel: 'elite',
    movementCategory: 'pull',
    supportsRPE: true,
    isIsometric: true,
    progressionDown: 'one_leg_fl',
    progressionLadder: 'front_lever',
    substitutionOptions: ['one_leg_fl', 'adv_tuck_fl'],
  },
  {
    id: 'banded_fl_hold',
    name: 'Banded Front Lever Hold',
    category: 'skill',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings', 'bands'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '15-20s',
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Band-assisted full FL position',
  },
  // ===== HSPU PROGRESSIONS =====
  {
    id: 'wall_hs_hold',
    name: 'Wall Handstand Hold',
    category: 'skill',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'core'],
    equipment: ['wall'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '30-45s',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Foundation handstand practice',
  },
  {
    id: 'wall_hspu_partial',
    name: 'Wall HSPU (Partial)',
    category: 'skill',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'chest'],
    equipment: ['wall'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '5-8',
    alternatives: ['wall_hspu_full'],
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Half range HSPU',
  },
  {
    id: 'wall_hspu_full',
    name: 'Wall HSPU (Full ROM)',
    category: 'skill',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'chest'],
    equipment: ['wall'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '4-6',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Head to floor full ROM',
  },
  {
    id: 'freestanding_hs_hold',
    name: 'Freestanding Handstand Hold',
    category: 'skill',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'core'],
    equipment: ['floor'],
    neuralDemand: 5,
    fatigueCost: 3,
    transferTo: ['handstand_pushup'],
    defaultSets: 5,
    defaultRepsOrTime: '15-30s',
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Balance-focused handstand work',
  },
  // ===== MUSCLE UP PROGRESSIONS =====
  {
    id: 'high_pulls',
    name: 'High Pull-Ups',
    category: 'skill',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps', 'rear_deltoid'],
    equipment: ['pull_bar'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '5-6',
    notes: 'Pull to chest/sternum',
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
  },
  {
    id: 'muscle_up_negative_skill',
    name: 'Muscle Up Negatives (Skill)',
    category: 'skill',
    movementPattern: 'transition',
    primaryMuscles: ['lats', 'chest', 'triceps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '3-4',
    notes: 'Controlled 3-4s descent',
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
  },
  {
    id: 'strict_muscle_up',
    name: 'Strict Muscle Ups',
    category: 'skill',
    movementPattern: 'transition',
    primaryMuscles: ['lats', 'chest', 'triceps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '3-5',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
  },
  {
    id: 'ring_muscle_up',
    name: 'Ring Muscle Ups',
    category: 'skill',
    movementPattern: 'transition',
    primaryMuscles: ['lats', 'chest', 'triceps'],
    equipment: ['rings'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '3-5',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Ring MU with false grip',
  },
]

// =============================================================================
// STRENGTH EXERCISES - Primary strength builders
// =============================================================================
export const STRENGTH_EXERCISES: Exercise[] = [
  // ===== PULL STRENGTH =====
  {
    id: 'weighted_pull_up',
    name: 'Weighted Pull-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps', 'rear_deltoid'],
    equipment: ['pull_bar'],
    neuralDemand: 3,
    fatigueCost: 4,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '5',
    notes: 'Primary pull strength builder',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
  },
  {
    id: 'chin_up',
    name: 'Chin-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps', 'brachialis'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '8-10',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Supinated grip, strong bicep emphasis',
  },
  {
    id: 'chest_to_bar_pull_up',
    name: 'Chest-to-Bar Pull-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'rear_deltoid', 'rhomboids'],
    equipment: ['pull_bar'],
    neuralDemand: 3,
    fatigueCost: 4,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '5-8',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Full ROM pull with chest contact',
  },
  {
    id: 'archer_pull_up',
    name: 'Archer Pull-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps', 'core'],
    equipment: ['pull_bar'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '4-6 each side',
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Unilateral pull progression',
  },
  {
    id: 'typewriter_pull_up',
    name: 'Typewriter Pull-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps', 'core'],
    equipment: ['pull_bar'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '4-6 each side',
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Side-to-side pull at top position',
  },
  {
    id: 'ring_row_elevated',
    name: 'Ring Rows (Elevated)',
    category: 'strength',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'rear_deltoid', 'biceps'],
    equipment: ['rings'],
    neuralDemand: 2,
    fatigueCost: 3,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '8-12',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Feet elevated for increased difficulty',
  },
  {
    id: 'tuck_front_lever_pull',
    name: 'Tuck Front Lever Pulls',
    category: 'strength',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'rear_deltoid'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '5-8',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    supportsBandAssistance: true,
    notes: 'Dynamic FL strength builder',
  },
  {
    id: 'one_arm_row_progression',
    name: 'One-Arm Row Progression',
    category: 'strength',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'biceps', 'core'],
    equipment: ['rings', 'pull_bar'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '6-8 each',
    difficultyLevel: 'advanced',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Unilateral horizontal pull',
  },
  // ===== PUSH STRENGTH =====
  {
    id: 'weighted_dip',
    name: 'Weighted Dips',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['dip_bars', 'rings'],
    neuralDemand: 3,
    fatigueCost: 4,
    transferTo: ['planche', 'muscle_up', 'handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '5',
    notes: 'Primary push strength builder',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
  },
  {
    id: 'ring_dip',
    name: 'Ring Dips',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['rings'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['planche', 'muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '6-10',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    supportsBandAssistance: true,
    notes: 'Unstable push requiring stabilization',
  },
  {
    id: 'ring_push_up',
    name: 'Ring Push-Ups',
    category: 'strength',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['rings'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '8-12',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Turn rings out at top for full activation',
  },
  {
    id: 'archer_push_up',
    name: 'Archer Push-Ups',
    category: 'strength',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['floor'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['planche'],
    defaultSets: 3,
    defaultRepsOrTime: '6-8 each side',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Unilateral push progression',
  },
  {
    id: 'pppu',
    name: 'Pseudo Planche Push-Ups',
    category: 'strength',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'triceps'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '6-8',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Keep lean angle throughout',
  },
  {
    id: 'planche_lean_pushup',
    name: 'Planche Lean Push-Ups',
    category: 'strength',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'triceps'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '4-6',
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Maximum lean angle push-ups',
  },
  {
    id: 'support_hold_dip_negative',
    name: 'Support Hold + Dip Negative',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['dip_bars', 'rings'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '5-8',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Eccentric control building',
  },
  {
    id: 'tuck_planche_pushup',
    name: 'Tuck Planche Push-Ups',
    category: 'strength',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['anterior_deltoid', 'chest', 'triceps'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['planche'],
    defaultSets: 4,
    defaultRepsOrTime: '4-6',
  },
  // Front Lever strength
  {
    id: 'fl_rows',
    name: 'Front Lever Rows',
    category: 'strength',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'rear_deltoid', 'biceps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 4,
    defaultRepsOrTime: '5-6',
    notes: 'Tuck or adv tuck position',
  },
  {
    id: 'ice_cream_maker',
    name: 'Ice Cream Makers',
    category: 'strength',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'core', 'biceps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '5-6',
    notes: 'Control both phases',
  },
  // ===== HSPU STRENGTH =====
  {
    id: 'pike_pushup',
    name: 'Pike Push-Ups',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Entry level vertical push',
    progressionUp: 'pike_pushup_elevated',
    progressionLadder: 'handstand_pushup',
    substitutionOptions: ['pike_pushup_elevated', 'shoulder_press'],
  },
  {
    id: 'pike_pushup_elevated',
    name: 'Pike Push-Ups (Elevated)',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps'],
    equipment: ['floor'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '8-10',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Feet elevated on box/chair',
    progressionUp: 'wall_hspu_negative',
    progressionDown: 'pike_pushup',
    progressionLadder: 'handstand_pushup',
    substitutionOptions: ['pike_pushup', 'wall_hspu_negative'],
  },
  {
    id: 'wall_hspu_negative',
    name: 'Wall HSPU Negatives',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'upper_chest'],
    equipment: ['wall'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '4-6',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Slow eccentric control',
    progressionUp: 'wall_hspu',
    progressionDown: 'pike_pushup_elevated',
    progressionLadder: 'handstand_pushup',
    substitutionOptions: ['pike_pushup_elevated', 'wall_hspu'],
  },
  {
    id: 'wall_hspu',
    name: 'Wall Handstand Push-Ups',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'upper_chest'],
    equipment: ['wall'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '5-8',
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Full range wall HSPU',
    progressionUp: 'deficit_hspu',
    progressionDown: 'wall_hspu_negative',
    progressionLadder: 'handstand_pushup',
    substitutionOptions: ['wall_hspu_negative', 'deficit_hspu'],
  },
  {
    id: 'deficit_hspu',
    name: 'Deficit Handstand Push-Ups',
    category: 'strength',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'triceps', 'upper_chest'],
    equipment: ['parallettes', 'wall'],
    neuralDemand: 4,
    fatigueCost: 5,
    transferTo: ['handstand_pushup'],
    defaultSets: 4,
    defaultRepsOrTime: '3-5',
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Extended ROM HSPU on parallettes',
    progressionUp: 'freestanding_hs_hold',
    progressionDown: 'wall_hspu',
    progressionLadder: 'handstand_pushup',
    substitutionOptions: ['wall_hspu'],
  },
  // ===== MUSCLE UP STRENGTH =====
  {
    id: 'straight_bar_dip',
    name: 'Straight Bar Dips',
    category: 'strength',
    movementPattern: 'transition',
    primaryMuscles: ['chest', 'triceps', 'core'],
    equipment: ['pull_bar'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '6-8',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Critical for muscle up transition',
  },
  {
    id: 'explosive_pull_up',
    name: 'Explosive Pull-Ups',
    category: 'strength',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps'],
    equipment: ['pull_bar'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '5-6',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Maximum acceleration',
  },
  {
    id: 'muscle_up_negative',
    name: 'Muscle-Up Negatives',
    category: 'strength',
    movementPattern: 'transition',
    primaryMuscles: ['lats', 'chest', 'triceps', 'core'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '3-5',
    difficultyLevel: 'intermediate',
    movementCategory: 'pull',
    supportsRPE: true,
    supportsBandAssistance: true,
    notes: 'Slow controlled descent through transition',
  },
  {
    id: 'muscle_up_transition_drill',
    name: 'Muscle-Up Transition Drill',
    category: 'strength',
    movementPattern: 'transition',
    primaryMuscles: ['chest', 'triceps', 'core'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['muscle_up'],
    defaultSets: 4,
    defaultRepsOrTime: '5-8',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    supportsBandAssistance: true,
    notes: 'Low bar/ring transition practice',
  },
]

// =============================================================================
// ACCESSORY EXERCISES - Support and volume work
// =============================================================================
export const ACCESSORY_EXERCISES: Exercise[] = [
  // ===== PULL ACCESSORIES =====
  {
    id: 'pull_up',
    name: 'Pull-Ups',
    category: 'accessory',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '8-12',
    supportsBandAssistance: true,
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Foundation vertical pull',
  },
  {
    id: 'bodyweight_row',
    name: 'Bodyweight Rows',
    category: 'accessory',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'rear_deltoid', 'biceps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Horizontal pull foundation',
  },
  {
    id: 'ring_row',
    name: 'Ring Rows',
    category: 'accessory',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'rear_deltoid', 'biceps'],
    equipment: ['rings'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Ring stability + horizontal pull',
  },
  {
    id: 'scap_pull_up',
    name: 'Scap Pull-Ups',
    category: 'accessory',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'lower_traps'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '10',
    notes: 'Focus on scap depression',
  },
  {
    id: 'hanging_shrug',
    name: 'Hanging Shrugs',
    category: 'accessory',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['upper_traps', 'lats'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['front_lever', 'muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '12-15',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: true,
    notes: 'Scap elevation control',
  },
  // ===== PUSH ACCESSORIES =====
  {
    id: 'dip',
    name: 'Dips',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['chest', 'triceps'],
    equipment: ['dip_bars', 'rings'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['planche', 'muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    supportsBandAssistance: true,
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
  },
  {
    id: 'push_up',
    name: 'Push-Ups',
    category: 'accessory',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps', 'anterior_deltoid'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche'],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Foundation horizontal push',
  },
  {
    id: 'diamond_pushup',
    name: 'Diamond Push-Ups',
    category: 'accessory',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['planche', 'handstand_pushup'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Tricep-dominant push',
  },
  {
    id: 'scap_pushup',
    name: 'Scap Push-Ups',
    category: 'accessory',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['serratus', 'core'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['planche'],
    defaultSets: 3,
    defaultRepsOrTime: '12-15',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: false,
    notes: 'Focus on scap protraction',
  },
  // ===== HSPU ACCESSORIES =====
  {
    id: 'wall_handstand_hold',
    name: 'Wall Handstand Hold',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'core', 'triceps'],
    equipment: ['wall'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 3,
    defaultRepsOrTime: '30-60s',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: false,
    isIsometric: true,
    notes: 'Build inverted comfort and shoulder stability',
  },
  {
    id: 'handstand_shoulder_taps',
    name: 'Handstand Shoulder Taps',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'core', 'obliques'],
    equipment: ['wall'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 3,
    defaultRepsOrTime: '10-16 taps',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    notes: 'Alternating shoulder taps in wall handstand',
  },
  {
    id: 'wall_scapula_shrug',
    name: 'Wall Scapula Shrugs',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['upper_traps', 'deltoids'],
    equipment: ['wall'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['handstand_pushup'],
    defaultSets: 3,
    defaultRepsOrTime: '12-15',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: false,
    notes: 'Scap elevation in wall handstand position',
  },
  {
    id: 'freestanding_handstand_hold',
    name: 'Freestanding Handstand Hold',
    category: 'skill',
    movementPattern: 'vertical_push',
    primaryMuscles: ['deltoids', 'core', 'triceps'],
    equipment: ['floor'],
    neuralDemand: 5,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 5,
    defaultRepsOrTime: '10-30s',
    difficultyLevel: 'advanced',
    movementCategory: 'push',
    supportsRPE: false,
    isIsometric: true,
    notes: 'Balance-focused freestanding handstand',
  },
  // ===== SUPPORT ACCESSORIES =====
  {
    id: 'support_hold',
    name: 'Support Hold',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['triceps', 'anterior_deltoid', 'core'],
    equipment: ['dip_bars', 'rings', 'parallettes'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['muscle_up', 'planche'],
    defaultSets: 3,
    defaultRepsOrTime: '30-45s',
    difficultyLevel: 'beginner',
    movementCategory: 'push',
    supportsRPE: false,
    isIsometric: true,
    notes: 'Foundation lockout position',
  },
  {
    id: 'ring_support_hold',
    name: 'Ring Support Hold',
    category: 'accessory',
    movementPattern: 'vertical_push',
    primaryMuscles: ['triceps', 'anterior_deltoid', 'core'],
    equipment: ['rings'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['muscle_up'],
    defaultSets: 3,
    defaultRepsOrTime: '20-30s',
    difficultyLevel: 'intermediate',
    movementCategory: 'push',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Ring stability with RTO',
  },
  {
    id: 'scapular_retraction_hold',
    name: 'Scapular Retraction Hold',
    category: 'accessory',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['rhomboids', 'lower_traps'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '20-30s',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: false,
    isIsometric: true,
    notes: 'Scap control for pulling',
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull Aparts',
    category: 'accessory',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['rear_deltoid', 'rhomboids'],
    equipment: ['bands'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: false,
    notes: 'Shoulder health and posture',
  },
  {
    id: 'face_pull',
    name: 'Face Pulls (Band)',
    category: 'accessory',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['rear_deltoid', 'rotator_cuff'],
    equipment: ['bands'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'pull',
    supportsRPE: false,
    notes: 'External rotation emphasis',
  },
  {
    id: 'shoulder_external_rotation',
    name: 'Shoulder External Rotation',
    category: 'accessory',
    movementPattern: 'mobility',
    primaryMuscles: ['rotator_cuff'],
    equipment: ['bands', 'floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '15 each',
    difficultyLevel: 'beginner',
    movementCategory: 'accessory',
    supportsRPE: false,
    notes: 'Rotator cuff prehab',
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    category: 'accessory',
    movementPattern: 'core',
    primaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche'],
    defaultSets: 3,
    defaultRepsOrTime: '12-15',
    difficultyLevel: 'beginner',
    movementCategory: 'accessory',
    supportsRPE: false,
    notes: 'Posterior chain activation',
  },
  {
    id: 'calf_raise',
    name: 'Calf Raises',
    category: 'accessory',
    movementPattern: 'core',
    primaryMuscles: ['calves'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'accessory',
    supportsRPE: false,
    notes: 'Lower leg balance work',
  },
  {
    id: 'wrist_prep_sequence',
    name: 'Wrist Prep Sequence',
    category: 'accessory',
    movementPattern: 'mobility',
    primaryMuscles: ['forearms', 'wrists'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche', 'handstand_pushup'],
    defaultSets: 1,
    defaultRepsOrTime: '2-3 min',
    difficultyLevel: 'beginner',
    movementCategory: 'accessory',
    supportsRPE: false,
    notes: 'Essential pre-handstand prep',
  },
]

// =============================================================================
// CORE EXERCISES - Essential body control and anti-rotation work
// =============================================================================
export const CORE_EXERCISES_POOL: Exercise[] = [
  // ===== HOLLOW/ARCH FOUNDATION =====
  {
    id: 'hollow_body',
    name: 'Hollow Body Hold',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['planche', 'front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '25-30s',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Foundation body line position',
  },
  {
    id: 'hollow_body_rock',
    name: 'Hollow Body Rocks',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['planche', 'front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Dynamic hollow control',
  },
  {
    id: 'arch_body',
    name: 'Arch Body Hold',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['erector_spinae', 'glutes'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '20-25s',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Posterior chain activation',
  },
  {
    id: 'side_hollow_hold',
    name: 'Side Hollow Hold',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['obliques', 'quadratus_lumborum'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['planche', 'front_lever'],
    defaultSets: 2,
    defaultRepsOrTime: '20s each side',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Lateral anti-rotation',
  },
  // ===== HANGING CORE =====
  {
    id: 'hanging_knee_raise',
    name: 'Hanging Knee Raises',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Entry hanging core',
  },
  {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raises',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '8-10',
    difficultyLevel: 'intermediate',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Full ROM hip flexion',
  },
  {
    id: 'toes_to_bar',
    name: 'Toes to Bar',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis', 'lats'],
    equipment: ['pull_bar'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '6-10',
    difficultyLevel: 'intermediate',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Max compression + control',
  },
  {
    id: 'hanging_l_sit',
    name: 'Hanging L-Sit',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis'],
    equipment: ['pull_bar', 'rings'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15s',
    difficultyLevel: 'intermediate',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Compression in hang',
  },
  // ===== DRAGON FLAG =====
  {
    id: 'dragon_flag_neg',
    name: 'Dragon Flag Negatives',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['rectus_abdominis', 'obliques'],
    equipment: ['floor'],
    neuralDemand: 3,
    fatigueCost: 3,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '5-6',
    supportsBandAssistance: true,
    difficultyLevel: 'intermediate',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Eccentric full body control',
  },
  {
    id: 'dragon_flag',
    name: 'Dragon Flags',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['rectus_abdominis', 'obliques', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '4-6',
    supportsBandAssistance: true,
    difficultyLevel: 'advanced',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Full dragon flag both phases',
  },
  // ===== ANTI-EXTENSION =====
  {
    id: 'reverse_plank_raise',
    name: 'Reverse Plank Raises',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['glutes', 'hamstrings', 'erector_spinae'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Posterior chain hip extension',
  },
  {
    id: 'reverse_crunch',
    name: 'Reverse Crunches',
    category: 'core',
    movementPattern: 'core',
    primaryMuscles: ['rectus_abdominis', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 3,
    defaultRepsOrTime: '12-15',
    difficultyLevel: 'beginner',
    movementCategory: 'core',
    supportsRPE: true,
    notes: 'Lower abs emphasis',
  },
  // ===== COMPRESSION/HIP FLEXOR CORE =====
  {
    id: 'l_sit_core',
    name: 'L-Sit Hold',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis', 'triceps'],
    equipment: ['floor', 'parallettes'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['planche', 'l_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15s',
    difficultyLevel: 'intermediate',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
  },
  {
    id: 'compression_work',
    name: 'Pike Compression Lifts',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'rectus_abdominis'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['planche', 'v_sit', 'l_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-12',
    difficultyLevel: 'beginner',
    movementCategory: 'compression',
    supportsRPE: true,
    notes: 'Foundation compression strength',
  },
  {
    id: 'seated_leg_lift',
    name: 'Seated Leg Lifts',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'quads'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15 each',
    difficultyLevel: 'beginner',
    movementCategory: 'compression',
    supportsRPE: true,
    notes: 'Single leg compression',
  },
  {
    id: 'straddle_compression_lift',
    name: 'Straddle Compression Lifts',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'adductors'],
    equipment: ['floor'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '8-12',
    difficultyLevel: 'intermediate',
    movementCategory: 'compression',
    supportsRPE: true,
    notes: 'Wide leg compression',
  },
  {
    id: 'compression_pulse',
    name: 'Compression Pulses',
    category: 'core',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '15-20',
    difficultyLevel: 'beginner',
    movementCategory: 'compression',
    supportsRPE: true,
    notes: 'Active compression endurance',
  },
]

// =============================================================================
// WARMUP EXERCISES
// =============================================================================
export const WARMUP_EXERCISES: Exercise[] = [
  {
    id: 'wrist_circles',
    name: 'Wrist Circles',
    category: 'warmup',
    movementPattern: 'skill',
    primaryMuscles: ['forearms'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '10 each direction',
  },
  {
    id: 'arm_circles',
    name: 'Arm Circles',
    category: 'warmup',
    movementPattern: 'skill',
    primaryMuscles: ['deltoids'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '10 each direction',
  },
  {
    id: 'band_pull_apart',
    name: 'Band Pull Aparts',
    category: 'warmup',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['rear_deltoid', 'rhomboids'],
    equipment: ['bands'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '15',
  },
  {
    id: 'scap_pushup_warmup',
    name: 'Scap Push-Ups',
    category: 'warmup',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['serratus'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '10',
  },
  {
    id: 'dead_hang',
    name: 'Dead Hang',
    category: 'warmup',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['forearms', 'lats'],
    equipment: ['pull_bar'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '30s',
  },
  {
    id: 'active_hang',
    name: 'Active Hang',
    category: 'warmup',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'lower_traps'],
    equipment: ['pull_bar'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '15s',
  },
]

// =============================================================================
// COMPRESSION SKILL EXERCISES - L-sit, V-sit, I-sit pathway
// =============================================================================
export const COMPRESSION_EXERCISES: Exercise[] = [
  // ===== L-SIT PROGRESSION =====
  {
    id: 'tuck_l_sit',
    name: 'Tuck L-Sit Hold',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'triceps'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['l_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15s',
    difficultyLevel: 'beginner',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Entry level compression skill',
  },
  {
    id: 'single_leg_l_sit',
    name: 'Single Leg L-Sit',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'triceps'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['l_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '8-12s each',
    difficultyLevel: 'intermediate',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'One leg extended progression',
  },
  {
    id: 'l_sit_skill',
    name: 'L-Sit Hold (Skill)',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'triceps'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 4,
    fatigueCost: 3,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 4,
    defaultRepsOrTime: '15-20s',
    difficultyLevel: 'intermediate',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Full L-sit with straight legs',
  },
  {
    id: 'advanced_l_sit',
    name: 'Advanced L-Sit Hold',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'triceps'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 4,
    fatigueCost: 4,
    transferTo: ['v_sit'],
    defaultSets: 4,
    defaultRepsOrTime: '20-25s',
    difficultyLevel: 'advanced',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    alternatives: ['v_sit_progression'],
    notes: 'Maximum hip flexion angle',
  },
  // ===== V-SIT PROGRESSION =====
  {
    id: 'v_sit_progression',
    name: 'V-Sit Progression',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'shoulders'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 5,
    fatigueCost: 4,
    transferTo: ['v_sit', 'i_sit'],
    defaultSets: 4,
    defaultRepsOrTime: '8-12s',
    difficultyLevel: 'advanced',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Increasing leg height toward V',
  },
  {
    id: 'v_sit_hold',
    name: 'V-Sit Hold',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['core', 'hip_flexors', 'shoulders'],
    equipment: ['parallettes', 'dip_bars'],
    neuralDemand: 5,
    fatigueCost: 5,
    transferTo: ['v_sit', 'i_sit'],
    defaultSets: 4,
    defaultRepsOrTime: '5-10s',
    difficultyLevel: 'elite',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Full V-sit position',
  },
  // ===== MANNA PROGRESSION =====
  {
    id: 'manna_progression',
    name: 'Manna Progression',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'shoulders', 'core'],
    equipment: ['parallettes', 'floor'],
    neuralDemand: 5,
    fatigueCost: 5,
    transferTo: ['i_sit'],
    defaultSets: 4,
    defaultRepsOrTime: '3-6s',
    difficultyLevel: 'elite',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Ultimate compression skill',
  },
  // ===== COMPRESSION FOLD HOLDS =====
  {
    id: 'compression_fold_hold',
    name: 'Compression Fold Hold',
    category: 'skill',
    movementPattern: 'compression',
    primaryMuscles: ['hip_flexors', 'core'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '20-30s',
    difficultyLevel: 'beginner',
    movementCategory: 'compression',
    supportsRPE: true,
    isIsometric: true,
    notes: 'Passive to active fold transition',
  },
]

// =============================================================================
// UTILITY FUNCTIONS - Get exercises by category
// =============================================================================

// =============================================================================
// COOLDOWN EXERCISES
// =============================================================================
export const COOLDOWN_EXERCISES: Exercise[] = [
  {
    id: 'shoulder_stretch',
    name: 'Shoulder Stretch',
    category: 'cooldown',
    movementPattern: 'mobility',
    primaryMuscles: ['deltoids'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '30s each',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
  },
  {
    id: 'wrist_stretches',
    name: 'Wrist Stretches',
    category: 'cooldown',
    movementPattern: 'mobility',
    primaryMuscles: ['forearms'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '30s each position',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
  },
  {
    id: 'lat_stretch',
    name: 'Lat Stretch',
    category: 'cooldown',
    movementPattern: 'mobility',
    primaryMuscles: ['lats'],
    equipment: ['floor', 'pull_bar'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '30s each',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
  },
  {
    id: 'chest_stretch',
    name: 'Chest Stretch',
    category: 'cooldown',
    movementPattern: 'mobility',
    primaryMuscles: ['chest'],
    equipment: ['floor', 'wall'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 1,
    defaultRepsOrTime: '30s each',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
  },
]

// =============================================================================
// FLEXIBILITY EXERCISES - Dedicated mobility and flexibility drills
// =============================================================================
export const FLEXIBILITY_EXERCISES: Exercise[] = [
  // ===== PIKE/HAMSTRING FLEXIBILITY =====
  {
    id: 'pike_stretch',
    name: 'Pike Stretch',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hamstrings', 'lower_back'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '60s',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Seated forward fold for hamstring flexibility',
  },
  {
    id: 'forward_fold_hold',
    name: 'Standing Forward Fold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hamstrings', 'calves', 'lower_back'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['l_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '45-60s',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Relaxed standing toe touch',
  },
  {
    id: 'standing_toe_touch',
    name: 'Standing Toe Touch (Active)',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['l_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '10-15',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    notes: 'Active hamstring ROM drill',
  },
  {
    id: 'hamstring_fold',
    name: 'Hamstring Fold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '60s each',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Single leg hamstring stretch',
  },
  // ===== PANCAKE/STRADDLE FLEXIBILITY =====
  {
    id: 'pancake_stretch',
    name: 'Pancake Stretch',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hamstrings', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['v_sit', 'i_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '60s',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Straddle forward fold for middle split progress',
  },
  {
    id: 'seated_pancake_hold',
    name: 'Seated Pancake Hold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['v_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '45-60s',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Deep straddle hold',
  },
  {
    id: 'active_pancake_lean',
    name: 'Active Pancake Lean',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hamstrings', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: ['v_sit', 'i_sit'],
    defaultSets: 3,
    defaultRepsOrTime: '30s each direction',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Lean forward + side in straddle',
  },
  {
    id: 'straddle_fold',
    name: 'Straddle Fold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '60s',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Side straddle fold stretch',
  },
  // ===== SPLIT PREPARATION =====
  {
    id: 'front_split_prep',
    name: 'Front Split Prep',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'hamstrings'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '60s each',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Progressive front split work',
  },
  {
    id: 'side_split_prep',
    name: 'Side Split Prep',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '60s',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Progressive middle split work',
  },
  // ===== HIP FLEXIBILITY =====
  {
    id: 'cossack_hold',
    name: 'Cossack Squat Hold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hip_flexors', 'glutes'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '30s each side',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Lateral hip and adductor stretch',
  },
  {
    id: 'butterfly_groin_stretch',
    name: 'Butterfly Stretch',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['adductors', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '60s',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Groin opener',
  },
  {
    id: 'hip_flexor_stretch_flex',
    name: 'Hip Flexor Stretch',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'quads'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche'],
    defaultSets: 2,
    defaultRepsOrTime: '60s each side',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Lunge position hip flexor stretch',
  },
  // ===== SHOULDER FLEXIBILITY =====
  {
    id: 'shoulder_dislocates',
    name: 'Shoulder Dislocates',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['shoulders', 'chest'],
    equipment: ['bands', 'floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche', 'handstand_pushup'],
    defaultSets: 2,
    defaultRepsOrTime: '10-15',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    notes: 'Use stick or band for shoulder mobility',
  },
  {
    id: 'german_hang',
    name: 'German Hang',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['shoulders', 'biceps', 'chest'],
    equipment: ['rings', 'pull_bar'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['muscle_up', 'front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '20-30s',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Shoulder extension stretch in hang position',
  },
  {
    id: 'skin_the_cat',
    name: 'Skin the Cat',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['shoulders', 'lats', 'core'],
    equipment: ['rings', 'pull_bar'],
    neuralDemand: 3,
    fatigueCost: 2,
    transferTo: ['muscle_up', 'front_lever'],
    defaultSets: 3,
    defaultRepsOrTime: '3-5',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    notes: 'Full shoulder rotation through hang',
  },
  // ===== WRIST/FOREARM FLEXIBILITY =====
  {
    id: 'wrist_flexibility',
    name: 'Wrist Flexibility Routine',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['forearms', 'wrists'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['planche', 'handstand_pushup'],
    defaultSets: 1,
    defaultRepsOrTime: '3-5 min',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    notes: 'Essential for handstand and planche work',
  },
  // ===== SPINE FLEXIBILITY =====
  {
    id: 'thoracic_bridge',
    name: 'Thoracic Bridge',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['spine', 'shoulders', 'hip_flexors'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['handstand_pushup'],
    defaultSets: 3,
    defaultRepsOrTime: '15-30s',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Full bridge for thoracic spine mobility',
  },
  {
    id: 'jefferson_curl',
    name: 'Jefferson Curl',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['spine', 'hamstrings'],
    equipment: ['floor'],
    neuralDemand: 2,
    fatigueCost: 2,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '8-10',
    difficultyLevel: 'intermediate',
    movementCategory: 'flexibility',
    notes: 'Controlled spinal flexion for posterior chain flexibility',
  },
  // ===== DYNAMIC FLEXIBILITY =====
  {
    id: 'elephant_walk',
    name: 'Elephant Walk',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hamstrings', 'calves', 'shoulders'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: ['l_sit', 'v_sit'],
    defaultSets: 2,
    defaultRepsOrTime: '10-15 steps',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    notes: 'Dynamic hamstring and pike mobility',
  },
  {
    id: 'deep_squat_hold',
    name: 'Deep Squat Hold',
    category: 'flexibility',
    movementPattern: 'mobility',
    primaryMuscles: ['hip_flexors', 'ankles', 'glutes'],
    equipment: ['floor'],
    neuralDemand: 1,
    fatigueCost: 1,
    transferTo: [],
    defaultSets: 2,
    defaultRepsOrTime: '60-90s',
    difficultyLevel: 'beginner',
    movementCategory: 'flexibility',
    isIsometric: true,
    notes: 'Full depth squat for hip and ankle mobility',
  },
]

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getAllExercises(): Exercise[] {
  return [
    ...SKILL_EXERCISES,
    ...STRENGTH_EXERCISES,
    ...ACCESSORY_EXERCISES,
    ...CORE_EXERCISES_POOL,
    ...WARMUP_EXERCISES,
    ...COOLDOWN_EXERCISES,
    ...COMPRESSION_EXERCISES,
    ...FLEXIBILITY_EXERCISES,
  ]
}

export function getExerciseById(id: string): Exercise | undefined {
  return getAllExercises().find(e => e.id === id)
}

export function getExercisesByTransfer(skillId: string): Exercise[] {
  return getAllExercises().filter(e => e.transferTo.includes(skillId))
}

export function getExercisesByCategory(category: ExerciseCategory): Exercise[] {
  return getAllExercises().filter(e => e.category === category)
}

export function getExercisesByMovement(pattern: MovementPattern): Exercise[] {
  return getAllExercises().filter(e => e.movementPattern === pattern)
}

export function hasRequiredEquipment(exercise: Exercise, available: EquipmentType[]): boolean {
  // Floor and wall are always available
  const alwaysAvailable: EquipmentType[] = ['floor', 'wall']
  const allAvailable = [...alwaysAvailable, ...available]
  
  return exercise.equipment.some(eq => allAvailable.includes(eq))
}

// =============================================================================
// ENHANCED FILTERING FOR PROGRAM BUILDER
// =============================================================================

/**
 * Filter exercises by difficulty level
 */
export function getExercisesByDifficulty(difficulty: DifficultyLevel): Exercise[] {
  return getAllExercises().filter(e => e.difficultyLevel === difficulty)
}

/**
 * Filter exercises by movement category (push/pull/compression)
 */
export function getExercisesByMovementCategory(category: MovementCategory): Exercise[] {
  return getAllExercises().filter(e => e.movementCategory === category)
}

/**
 * Get exercises that support band assistance
 */
export function getBandAssistedExercises(): Exercise[] {
  return getAllExercises().filter(e => e.supportsBandAssistance === true)
}

/**
 * Get exercises that support RPE tracking
 */
export function getRPETrackableExercises(): Exercise[] {
  return getAllExercises().filter(e => e.supportsRPE !== false)
}

/**
 * Get isometric/hold exercises
 */
export function getIsometricExercises(): Exercise[] {
  return getAllExercises().filter(e => e.isIsometric === true)
}

/**
 * Infer difficulty level from exercise characteristics
 */
export function inferDifficultyLevel(exercise: Exercise): DifficultyLevel {
  if (exercise.difficultyLevel) return exercise.difficultyLevel
  
  const demand = exercise.neuralDemand + exercise.fatigueCost
  if (demand <= 4) return 'beginner'
  if (demand <= 6) return 'intermediate'
  if (demand <= 8) return 'advanced'
  return 'elite'
}

/**
 * Infer movement category from movement pattern
 */
export function inferMovementCategory(exercise: Exercise): MovementCategory {
  if (exercise.movementCategory) return exercise.movementCategory
  
  const pattern = exercise.movementPattern
  if (pattern === 'horizontal_push' || pattern === 'vertical_push') return 'push'
  if (pattern === 'horizontal_pull' || pattern === 'vertical_pull') return 'pull'
  if (pattern === 'compression') return 'compression'
  if (pattern === 'core') return 'core'
  if (pattern === 'mobility') return 'flexibility'
  
  // Fallback based on category
  if (exercise.category === 'warmup') return 'warmup'
  if (exercise.category === 'cooldown') return 'cooldown'
  
  return 'accessory'
}

/**
 * Check if exercise is a hold/isometric
 */
export function isIsometricExercise(exercise: Exercise): boolean {
  if (exercise.isIsometric !== undefined) return exercise.isIsometric
  // Infer from repsOrTime format
  return exercise.defaultRepsOrTime.includes('s') || exercise.defaultRepsOrTime.includes('sec')
}

/**
 * Multi-criteria exercise filter for Program Builder
 */
export interface ExerciseFilterCriteria {
  categories?: ExerciseCategory[]
  movementPatterns?: MovementPattern[]
  movementCategories?: MovementCategory[]
  difficultyLevels?: DifficultyLevel[]
  equipment?: EquipmentType[]
  supportsBands?: boolean
  supportsRPE?: boolean
  isIsometric?: boolean
  transfersTo?: string[]
  maxFatigueCost?: number
  maxNeuralDemand?: number
}

/**
 * Filter exercises using multiple criteria
 */
export function filterExercises(criteria: ExerciseFilterCriteria): Exercise[] {
  let exercises = getAllExercises()
  
  if (criteria.categories?.length) {
    exercises = exercises.filter(e => criteria.categories!.includes(e.category))
  }
  
  if (criteria.movementPatterns?.length) {
    exercises = exercises.filter(e => criteria.movementPatterns!.includes(e.movementPattern))
  }
  
  if (criteria.movementCategories?.length) {
    exercises = exercises.filter(e => {
      const cat = inferMovementCategory(e)
      return criteria.movementCategories!.includes(cat)
    })
  }
  
  if (criteria.difficultyLevels?.length) {
    exercises = exercises.filter(e => {
      const level = inferDifficultyLevel(e)
      return criteria.difficultyLevels!.includes(level)
    })
  }
  
  if (criteria.equipment?.length) {
    exercises = exercises.filter(e => hasRequiredEquipment(e, criteria.equipment!))
  }
  
  if (criteria.supportsBands !== undefined) {
    exercises = exercises.filter(e => 
      criteria.supportsBands ? e.supportsBandAssistance === true : true
    )
  }
  
  if (criteria.supportsRPE !== undefined) {
    exercises = exercises.filter(e => 
      criteria.supportsRPE ? e.supportsRPE !== false : true
    )
  }
  
  if (criteria.isIsometric !== undefined) {
    exercises = exercises.filter(e => isIsometricExercise(e) === criteria.isIsometric)
  }
  
  if (criteria.transfersTo?.length) {
    exercises = exercises.filter(e => 
      e.transferTo.some(t => criteria.transfersTo!.includes(t))
    )
  }
  
  if (criteria.maxFatigueCost !== undefined) {
    exercises = exercises.filter(e => e.fatigueCost <= criteria.maxFatigueCost!)
  }
  
  if (criteria.maxNeuralDemand !== undefined) {
    exercises = exercises.filter(e => e.neuralDemand <= criteria.maxNeuralDemand!)
  }
  
  return exercises
}

/**
 * Get a balanced exercise selection across movement categories
 */
export function getBalancedExerciseSelection(
  targetCount: number,
  criteria: ExerciseFilterCriteria = {}
): Exercise[] {
  const filtered = filterExercises(criteria)
  
  // Group by movement category
  const byCategory: Record<MovementCategory, Exercise[]> = {
    push: [],
    pull: [],
    compression: [],
    core: [],
    flexibility: [],
    accessory: [],
    warmup: [],
    cooldown: [],
  }
  
  filtered.forEach(e => {
    const cat = inferMovementCategory(e)
    byCategory[cat].push(e)
  })
  
  // Select balanced mix (prioritize push/pull/compression)
  const result: Exercise[] = []
  const priorities: MovementCategory[] = ['push', 'pull', 'compression', 'core', 'accessory', 'flexibility']
  
  let idx = 0
  while (result.length < targetCount && idx < priorities.length * targetCount) {
    const cat = priorities[idx % priorities.length]
    const available = byCategory[cat].filter(e => !result.includes(e))
    if (available.length > 0) {
      result.push(available[0])
    }
    idx++
  }
  
  return result
}
