/**
 * Advanced Skill Progression Graphs
 * 
 * Extended progression graphs for elite calisthenics skills:
 * - Maltese
 * - Planche Push-Ups
 * - Front Lever Pull-Ups
 * - Slow Muscle-Up
 * - Weighted Muscle-Up
 */

import type { SkillProgressionGraph, ProgressionNode } from './skill-progression-graph-engine'

// =============================================================================
// MALTESE PROGRESSION GRAPH
// =============================================================================

export const MALTESE_GRAPH: SkillProgressionGraph = {
  skillId: 'maltese',
  skillName: 'Maltese',
  description: 'Advanced straight-arm hold on rings requiring elite shoulder stability and strength',
  movementFamily: 'straight_arm_push',
  entryNode: 'mal_1_ring_support',
  terminalNode: 'mal_7_full',
  nodes: [
    {
      nodeId: 'mal_1_ring_support',
      skillId: 'maltese',
      nodeName: 'ring_support_hold',
      displayName: 'Ring Support Hold',
      description: 'Foundation: comfortable ring support stability',
      difficultyLevel: 'foundation',
      levelIndex: 0,
      movementType: 'isometric_hold',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 30, unit: 'seconds', description: 'Ring support 30s+' }],
      requiredReadinessScore: 40,
      requiredPrerequisiteNodes: [],
      minimumForOwnership: 30,
      knowledgeBubble: { shortTip: 'Develop ring support stability', fullExplanation: 'Ring support is the foundation for all advanced ring strength work, especially Maltese.' },
      jointStressLevel: 'moderate',
      primaryWeakPointFocus: 'ring_support',
    },
    {
      nodeId: 'mal_2_wide_support',
      skillId: 'maltese',
      nodeName: 'wide_ring_support',
      displayName: 'Wide Ring Support',
      description: 'Wider hand position increases arm leverage and shoulder demand',
      difficultyLevel: 'intermediate',
      levelIndex: 1,
      movementType: 'isometric_hold',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 45, unit: 'seconds', description: 'Ring support 45s+' }],
      requiredReadinessScore: 55,
      requiredPrerequisiteNodes: ['mal_1_ring_support'],
      minimumForOwnership: 20,
      knowledgeBubble: { shortTip: 'Prepare for Maltese entry', fullExplanation: 'Wider grip increases straight-arm demand and prepares shoulders for the full hold.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'mal_3_assisted_hold',
      skillId: 'maltese',
      nodeName: 'assisted_maltese_support',
      displayName: 'Assisted Maltese Support',
      description: 'Bands or straps assist the hold, developing strength safely',
      difficultyLevel: 'intermediate',
      levelIndex: 2,
      movementType: 'assisted',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 60, unit: 'seconds', description: 'Wide ring support 60s+' }],
      requiredReadinessScore: 65,
      requiredPrerequisiteNodes: ['mal_2_wide_support'],
      minimumForOwnership: 20,
      knowledgeBubble: { shortTip: 'Build strength with support', fullExplanation: 'Assisted variations allow tendon adaptation without undue risk.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'shoulder_stability',
    },
    {
      nodeId: 'mal_4_band_assisted',
      skillId: 'maltese',
      nodeName: 'band_assisted_maltese',
      displayName: 'Band-Assisted Maltese',
      description: 'Light band support, approaching unassisted position',
      difficultyLevel: 'advanced',
      levelIndex: 3,
      movementType: 'assisted',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 30, unit: 'seconds', description: 'Assisted Maltese 30s+' }],
      requiredReadinessScore: 75,
      requiredPrerequisiteNodes: ['mal_3_assisted_hold'],
      minimumForOwnership: 20,
      knowledgeBubble: { shortTip: 'Progress to unassisted', fullExplanation: 'Minimal support challenges full strength while maintaining safety.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'mal_5_negative',
      skillId: 'maltese',
      nodeName: 'maltese_negative',
      displayName: 'Maltese Negative',
      description: 'Controlled descent from assisted position',
      difficultyLevel: 'advanced',
      levelIndex: 4,
      movementType: 'negative',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 10, unit: 'seconds', description: 'Band-assisted Maltese 10s+' }],
      requiredReadinessScore: 80,
      requiredPrerequisiteNodes: ['mal_4_band_assisted'],
      minimumForOwnership: 5,
      knowledgeBubble: { shortTip: 'Build eccentric strength', fullExplanation: 'Negatives introduce near-maximal tension safely for tendon adaptation.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'shoulder_tendon',
    },
    {
      nodeId: 'mal_6_partial',
      skillId: 'maltese',
      nodeName: 'partial_maltese',
      displayName: 'Partial Maltese',
      description: 'Incomplete hold - arms not fully horizontal',
      difficultyLevel: 'elite',
      levelIndex: 5,
      movementType: 'isometric_hold',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 5, unit: 'seconds', description: 'Maltese negative 5s+' }],
      requiredReadinessScore: 85,
      requiredPrerequisiteNodes: ['mal_5_negative'],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Approach full hold', fullExplanation: 'Partial Maltese begins the progression to full unassisted position.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'mal_7_full',
      skillId: 'maltese',
      nodeName: 'full_maltese',
      displayName: 'Full Maltese',
      description: 'Arms fully horizontal, elite straight-arm strength display',
      difficultyLevel: 'master',
      levelIndex: 6,
      movementType: 'isometric_hold',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 2, unit: 'seconds', description: 'Partial Maltese 2s+' }],
      requiredReadinessScore: 90,
      requiredPrerequisiteNodes: ['mal_6_partial'],
      minimumForOwnership: 2,
      knowledgeBubble: { shortTip: 'Elite mastery', fullExplanation: 'Full Maltese is one of calisthenics highest achievements, requiring years of dedicated training.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
  ],
  edges: [
    { edgeId: 'mal_e1', fromNodeId: 'mal_1_ring_support', toNodeId: 'mal_2_wide_support', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 30, readinessThreshold: 55 }, expectedTransitionWeeks: 8, isRecommendedPath: true },
    { edgeId: 'mal_e2', fromNodeId: 'mal_2_wide_support', toNodeId: 'mal_3_assisted_hold', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 45, readinessThreshold: 65 }, expectedTransitionWeeks: 12, isRecommendedPath: true },
    { edgeId: 'mal_e3', fromNodeId: 'mal_3_assisted_hold', toNodeId: 'mal_4_band_assisted', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 30, readinessThreshold: 75 }, expectedTransitionWeeks: 16, isRecommendedPath: true },
    { edgeId: 'mal_e4', fromNodeId: 'mal_4_band_assisted', toNodeId: 'mal_5_negative', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 20, readinessThreshold: 80 }, expectedTransitionWeeks: 12, isRecommendedPath: true },
    { edgeId: 'mal_e5', fromNodeId: 'mal_5_negative', toNodeId: 'mal_6_partial', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 8, readinessThreshold: 85 }, expectedTransitionWeeks: 20, isRecommendedPath: true },
    { edgeId: 'mal_e6', fromNodeId: 'mal_6_partial', toNodeId: 'mal_7_full', transitionType: 'progression', minimumRequirements: { fromNodeHoldTime: 3, readinessThreshold: 90 }, expectedTransitionWeeks: 24, isRecommendedPath: true },
  ],
}

// =============================================================================
// PLANCHE PUSH-UP PROGRESSION GRAPH
// =============================================================================

export const PLANCHE_PUSHUP_GRAPH: SkillProgressionGraph = {
  skillId: 'planche_pushup',
  skillName: 'Planche Push-Up',
  description: 'Advanced dynamic straight-arm pressing from planche position',
  movementFamily: 'straight_arm_push',
  entryNode: 'ppu_1_pseudo_foundation',
  terminalNode: 'ppu_7_full',
  nodes: [
    {
      nodeId: 'ppu_1_pseudo_foundation',
      skillId: 'planche_pushup',
      nodeName: 'pseudo_planche_pushup_foundation',
      displayName: 'Pseudo Planche Push-Up Foundation',
      description: 'Build dynamic pressing strength with feet on ground',
      difficultyLevel: 'intermediate',
      levelIndex: 0,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 5, unit: 'reps', description: '5 quality push-ups' }],
      requiredReadinessScore: 50,
      requiredPrerequisiteNodes: [],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Dynamic planche base', fullExplanation: 'Pseudo planche push-ups build dynamic pressing strength and shoulder stability for planche progressions.' },
      jointStressLevel: 'moderate',
      primaryWeakPointFocus: 'dynamic_push',
    },
    {
      nodeId: 'ppu_2_elevated',
      skillId: 'planche_pushup',
      nodeName: 'elevated_pseudo_planche_pushup',
      displayName: 'Elevated Pseudo Planche Push-Up',
      description: 'Hands elevated to reduce body angle demand',
      difficultyLevel: 'intermediate',
      levelIndex: 1,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 8, unit: 'reps', description: '8+ pseudo planche push-ups' }],
      requiredReadinessScore: 60,
      requiredPrerequisiteNodes: ['ppu_1_pseudo_foundation'],
      minimumForOwnership: 5,
      knowledgeBubble: { shortTip: 'Progress the angle', fullExplanation: 'Elevated position increases demands while maintaining control.' },
      jointStressLevel: 'moderate',
      primaryWeakPointFocus: 'dynamic_push',
    },
    {
      nodeId: 'ppu_3_tuck_assisted',
      skillId: 'planche_pushup',
      nodeName: 'tuck_planche_pushup_assisted',
      displayName: 'Assisted Tuck Planche Push-Up',
      description: 'Tuck position with band or ring assistance',
      difficultyLevel: 'advanced',
      levelIndex: 2,
      movementType: 'assisted',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 10, unit: 'reps', description: '10+ elevated pseudo planche' }],
      requiredReadinessScore: 70,
      requiredPrerequisiteNodes: ['ppu_2_elevated'],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Assisted planche pressing', fullExplanation: 'Assistance allows exploration of planche position under load with safety.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'ppu_4_tuck',
      skillId: 'planche_pushup',
      nodeName: 'tuck_planche_pushup',
      displayName: 'Tuck Planche Push-Up',
      description: 'Unassisted tuck planche push-up',
      difficultyLevel: 'advanced',
      levelIndex: 3,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 2, unit: 'reps', description: '2+ assisted tuck' }],
      requiredReadinessScore: 80,
      requiredPrerequisiteNodes: ['ppu_3_tuck_assisted'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Real planche pressing', fullExplanation: 'Tuck planche push-ups represent significant dynamic strength achievement.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'ppu_5_adv_tuck',
      skillId: 'planche_pushup',
      nodeName: 'advanced_tuck_planche_pushup',
      displayName: 'Advanced Tuck Planche Push-Up',
      description: 'Increased leverage and control in tuck position',
      difficultyLevel: 'advanced',
      levelIndex: 4,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 5, unit: 'reps', description: '5+ tuck planche' }],
      requiredReadinessScore: 85,
      requiredPrerequisiteNodes: ['ppu_4_tuck'],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Build planche power', fullExplanation: 'Solid tuck planche mastery prepares for straddle progressions.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'ppu_6_straddle',
      skillId: 'planche_pushup',
      nodeName: 'straddle_planche_pushup',
      displayName: 'Straddle Planche Push-Up',
      description: 'Wider leg position increases difficulty',
      difficultyLevel: 'elite',
      levelIndex: 5,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 3, unit: 'reps', description: '3+ advanced tuck' }],
      requiredReadinessScore: 88,
      requiredPrerequisiteNodes: ['ppu_5_adv_tuck'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Elite straight-arm pressing', fullExplanation: 'Straddle planche push-up is a significant achievement in pressing strength.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
    {
      nodeId: 'ppu_7_full',
      skillId: 'planche_pushup',
      nodeName: 'full_planche_pushup',
      displayName: 'Full Planche Push-Up',
      description: 'Complete straight-arm planche push-up',
      difficultyLevel: 'master',
      levelIndex: 6,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 1, unit: 'reps', description: '1+ straddle planche' }],
      requiredReadinessScore: 90,
      requiredPrerequisiteNodes: ['ppu_6_straddle'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Ultimate achievement', fullExplanation: 'Full planche push-up represents mastery of dynamic straight-arm pressing.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_push',
    },
  ],
  edges: [
    { edgeId: 'ppu_e1', fromNodeId: 'ppu_1_pseudo_foundation', toNodeId: 'ppu_2_elevated', transitionType: 'progression', minimumRequirements: { fromNodeReps: 5, readinessThreshold: 60 }, expectedTransitionWeeks: 4, isRecommendedPath: true },
    { edgeId: 'ppu_e2', fromNodeId: 'ppu_2_elevated', toNodeId: 'ppu_3_tuck_assisted', transitionType: 'progression', minimumRequirements: { fromNodeReps: 8, readinessThreshold: 70 }, expectedTransitionWeeks: 6, isRecommendedPath: true },
    { edgeId: 'ppu_e3', fromNodeId: 'ppu_3_tuck_assisted', toNodeId: 'ppu_4_tuck', transitionType: 'progression', minimumRequirements: { fromNodeReps: 3, readinessThreshold: 80 }, expectedTransitionWeeks: 12, isRecommendedPath: true },
    { edgeId: 'ppu_e4', fromNodeId: 'ppu_4_tuck', toNodeId: 'ppu_5_adv_tuck', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 85 }, expectedTransitionWeeks: 8, isRecommendedPath: true },
    { edgeId: 'ppu_e5', fromNodeId: 'ppu_5_adv_tuck', toNodeId: 'ppu_6_straddle', transitionType: 'progression', minimumRequirements: { fromNodeReps: 4, readinessThreshold: 88 }, expectedTransitionWeeks: 16, isRecommendedPath: true },
    { edgeId: 'ppu_e6', fromNodeId: 'ppu_6_straddle', toNodeId: 'ppu_7_full', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 90 }, expectedTransitionWeeks: 24, isRecommendedPath: true },
  ],
}

// =============================================================================
// FRONT LEVER PULL-UP PROGRESSION GRAPH
// =============================================================================

export const FRONT_LEVER_PULLUP_GRAPH: SkillProgressionGraph = {
  skillId: 'front_lever_pullup',
  skillName: 'Front Lever Pull-Up',
  description: 'Advanced pulling variation combining front lever control with upward pull',
  movementFamily: 'straight_arm_pull',
  entryNode: 'flpu_1_tuck_row',
  terminalNode: 'flpu_6_one_arm_row',
  nodes: [
    {
      nodeId: 'flpu_1_tuck_row',
      skillId: 'front_lever_pullup',
      nodeName: 'tuck_fl_row',
      displayName: 'Tuck Front Lever Row',
      description: 'Front lever position with pulling emphasis',
      difficultyLevel: 'intermediate',
      levelIndex: 0,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'hold_time', minimumValue: 20, unit: 'seconds', description: 'Tuck front lever 20s+' }],
      requiredReadinessScore: 60,
      requiredPrerequisiteNodes: [],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Introduce dynamic pulling', fullExplanation: 'FL rows build pulling strength while maintaining lever control.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
    {
      nodeId: 'flpu_2_adv_tuck_row',
      skillId: 'front_lever_pullup',
      nodeName: 'advanced_tuck_fl_row',
      displayName: 'Advanced Tuck FL Row',
      description: 'Increased leverage demand in tuck position',
      difficultyLevel: 'advanced',
      levelIndex: 1,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 5, unit: 'reps', description: '5+ tuck FL rows' }],
      requiredReadinessScore: 70,
      requiredPrerequisiteNodes: ['flpu_1_tuck_row'],
      minimumForOwnership: 3,
      knowledgeBubble: { shortTip: 'Build dynamic pulling', fullExplanation: 'Progress pulling power while developing higher FL angles.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
    {
      nodeId: 'flpu_3_one_leg_row',
      skillId: 'front_lever_pullup',
      nodeName: 'one_leg_fl_row',
      displayName: 'One Leg FL Row',
      description: 'Single leg extends leverage significantly',
      difficultyLevel: 'advanced',
      levelIndex: 2,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 3, unit: 'reps', description: '3+ advanced tuck FL rows' }],
      requiredReadinessScore: 75,
      requiredPrerequisiteNodes: ['flpu_2_adv_tuck_row'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Increase leverage', fullExplanation: 'One-leg position dramatically increases difficulty while building progression toward full FL pull-ups.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
    {
      nodeId: 'flpu_4_straddle_row',
      skillId: 'front_lever_pullup',
      nodeName: 'straddle_fl_row',
      displayName: 'Straddle FL Row',
      description: 'Wide leg position in front lever pull',
      difficultyLevel: 'elite',
      levelIndex: 3,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 2, unit: 'reps', description: '2+ one-leg FL rows' }],
      requiredReadinessScore: 80,
      requiredPrerequisiteNodes: ['flpu_3_one_leg_row'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Approach full FL pull', fullExplanation: 'Straddle FL rows develop full pulling strength while maintaining control.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
    {
      nodeId: 'flpu_5_fl_pullup',
      skillId: 'front_lever_pullup',
      nodeName: 'front_lever_pullup',
      displayName: 'Front Lever Pull-Up',
      description: 'Full front lever pulling motion',
      difficultyLevel: 'elite',
      levelIndex: 4,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 1, unit: 'reps', description: '1+ straddle FL row' }],
      requiredReadinessScore: 85,
      requiredPrerequisiteNodes: ['flpu_4_straddle_row'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Elite achievement', fullExplanation: 'Front lever pull-up combines extreme pulling strength with full lever control.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
    {
      nodeId: 'flpu_6_one_arm_row',
      skillId: 'front_lever_pullup',
      nodeName: 'one_arm_fl_row',
      displayName: 'One-Arm Front Lever Row',
      description: 'Single-arm pulling from front lever position - ultimate achievement',
      difficultyLevel: 'master',
      levelIndex: 5,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 1, unit: 'reps', description: '1+ FL pull-up' }],
      requiredReadinessScore: 90,
      requiredPrerequisiteNodes: ['flpu_5_fl_pullup'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Mastery', fullExplanation: 'One-arm front lever row is one of the most difficult calisthenics achievements.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'straight_arm_pull',
    },
  ],
  edges: [
    { edgeId: 'flpu_e1', fromNodeId: 'flpu_1_tuck_row', toNodeId: 'flpu_2_adv_tuck_row', transitionType: 'progression', minimumRequirements: { fromNodeReps: 3, readinessThreshold: 70 }, expectedTransitionWeeks: 8, isRecommendedPath: true },
    { edgeId: 'flpu_e2', fromNodeId: 'flpu_2_adv_tuck_row', toNodeId: 'flpu_3_one_leg_row', transitionType: 'progression', minimumRequirements: { fromNodeReps: 5, readinessThreshold: 75 }, expectedTransitionWeeks: 12, isRecommendedPath: true },
    { edgeId: 'flpu_e3', fromNodeId: 'flpu_3_one_leg_row', toNodeId: 'flpu_4_straddle_row', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 80 }, expectedTransitionWeeks: 16, isRecommendedPath: true },
    { edgeId: 'flpu_e4', fromNodeId: 'flpu_4_straddle_row', toNodeId: 'flpu_5_fl_pullup', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 85 }, expectedTransitionWeeks: 20, isRecommendedPath: true },
    { edgeId: 'flpu_e5', fromNodeId: 'flpu_5_fl_pullup', toNodeId: 'flpu_6_one_arm_row', transitionType: 'progression', minimumRequirements: { fromNodeReps: 1, readinessThreshold: 90 }, expectedTransitionWeeks: 32, isRecommendedPath: true },
  ],
}

// =============================================================================
// SLOW MUSCLE-UP PROGRESSION GRAPH
// =============================================================================

export const SLOW_MUSCLE_UP_GRAPH: SkillProgressionGraph = {
  skillId: 'slow_muscle_up',
  skillName: 'Slow Muscle-Up',
  description: 'Muscle-up performed slowly with full control and reduced momentum',
  movementFamily: 'explosive_pull',
  entryNode: 'smu_1_strict',
  terminalNode: 'smu_5_weighted_moderate',
  nodes: [
    {
      nodeId: 'smu_1_strict',
      skillId: 'slow_muscle_up',
      nodeName: 'strict_muscle_up',
      displayName: 'Strict Muscle-Up',
      description: 'Muscle-up with full control, minimal kipping',
      difficultyLevel: 'advanced',
      levelIndex: 0,
      movementType: 'explosive',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 3, unit: 'reps', description: '3+ muscle-ups' }],
      requiredReadinessScore: 75,
      requiredPrerequisiteNodes: [],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Control foundation', fullExplanation: 'Strict muscle-ups develop the control foundation for slow variations.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'explosive_pull',
    },
    {
      nodeId: 'smu_2_slow',
      skillId: 'slow_muscle_up',
      nodeName: 'slow_muscle_up',
      displayName: 'Slow Muscle-Up',
      description: '3-5 second controlled muscle-up',
      difficultyLevel: 'elite',
      levelIndex: 1,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 2, unit: 'reps', description: '2+ strict muscle-ups' }],
      requiredReadinessScore: 82,
      requiredPrerequisiteNodes: ['smu_1_strict'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Slow control', fullExplanation: 'Slow muscle-ups significantly increase difficulty and develop tremendous pulling and pressing power.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'transition_control',
    },
    {
      nodeId: 'smu_3_tempo',
      skillId: 'slow_muscle_up',
      nodeName: 'tempo_slow_muscle_up',
      displayName: 'Tempo Slow Muscle-Up',
      description: '5+ second controlled muscle-up',
      difficultyLevel: 'elite',
      levelIndex: 2,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'reps', minimumValue: 1, unit: 'reps', description: '1+ slow muscle-up' }],
      requiredReadinessScore: 85,
      requiredPrerequisiteNodes: ['smu_2_slow'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Extreme control', fullExplanation: 'Tempo slow muscle-ups demand extraordinary strength and control.' },
      jointStressLevel: 'high',
      primaryWeakPointFocus: 'transition_control',
    },
    {
      nodeId: 'smu_4_weighted_light',
      skillId: 'slow_muscle_up',
      nodeName: 'weighted_muscle_up_light',
      displayName: 'Light Weighted Muscle-Up',
      description: 'Weighted muscle-up with 2.5-5kg load',
      difficultyLevel: 'elite',
      levelIndex: 3,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'weighted_dip', minimumValue: 10, unit: 'kg', description: 'Weighted dip +10kg' }],
      requiredReadinessScore: 85,
      requiredPrerequisiteNodes: ['smu_3_tempo'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Add load gradually', fullExplanation: 'Light weighted muscle-ups introduce load progression safely.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'explosive_pull',
    },
    {
      nodeId: 'smu_5_weighted_moderate',
      skillId: 'slow_muscle_up',
      nodeName: 'weighted_muscle_up_moderate',
      displayName: 'Moderate Weighted Muscle-Up',
      description: 'Weighted muscle-up with 5-10kg load',
      difficultyLevel: 'master',
      levelIndex: 4,
      movementType: 'dynamic_strength',
      requiredBenchmarks: [{ benchmarkType: 'weighted_dip', minimumValue: 20, unit: 'kg', description: 'Weighted dip +20kg' }],
      requiredReadinessScore: 88,
      requiredPrerequisiteNodes: ['smu_4_weighted_light'],
      minimumForOwnership: 1,
      knowledgeBubble: { shortTip: 'Increase load', fullExplanation: 'Moderate weighted muscle-ups significantly amplify strength development.' },
      jointStressLevel: 'very_high',
      primaryWeakPointFocus: 'explosive_pull',
    },
  ],
  edges: [
    { edgeId: 'smu_e1', fromNodeId: 'smu_1_strict', toNodeId: 'smu_2_slow', transitionType: 'progression', minimumRequirements: { fromNodeReps: 3, readinessThreshold: 82 }, expectedTransitionWeeks: 8, isRecommendedPath: true },
    { edgeId: 'smu_e2', fromNodeId: 'smu_2_slow', toNodeId: 'smu_3_tempo', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 85 }, expectedTransitionWeeks: 12, isRecommendedPath: true },
    { edgeId: 'smu_e3', fromNodeId: 'smu_3_tempo', toNodeId: 'smu_4_weighted_light', transitionType: 'progression', minimumRequirements: { fromNodeReps: 1, readinessThreshold: 85 }, expectedTransitionWeeks: 10, isRecommendedPath: true },
    { edgeId: 'smu_e4', fromNodeId: 'smu_4_weighted_light', toNodeId: 'smu_5_weighted_moderate', transitionType: 'progression', minimumRequirements: { fromNodeReps: 2, readinessThreshold: 88 }, expectedTransitionWeeks: 16, isRecommendedPath: true },
  ],
}
