/**
 * SpartanLab Exercise Classification Registry
 * 
 * Central source of truth for exercise classifications.
 * Maps exercise IDs to their movement families, intents, equipment, and skill carryover.
 * 
 * This registry enables:
 * - Intelligent substitutions that preserve training purpose
 * - Equipment-aware programming
 * - Skill-specific accessory selection
 * - Time-constrained workout optimization
 */

import {
  type MovementFamily,
  type TrainingIntent,
  type SkillCarryover,
  type EquipmentTag,
  type DifficultyBand,
  type ExerciseClassification,
  MOVEMENT_FAMILY_METADATA,
  SKILL_CARRYOVER_METADATA,
  TRAINING_INTENT_METADATA,
} from './movement-family-registry'

// =============================================================================
// EXERCISE CLASSIFICATION REGISTRY
// =============================================================================

/**
 * Complete exercise classifications
 * Each entry provides full metadata for intelligent exercise handling
 */
export const EXERCISE_CLASSIFICATIONS: Record<string, ExerciseClassification> = {
  // =========================================================================
  // VERTICAL PULL EXERCISES
  // =========================================================================
  'pull_up': {
    id: 'pull_up',
    name: 'Pull-Up',
    primaryFamily: 'vertical_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'muscle_up', 'one_arm_pull_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['chin_up', 'neutral_grip_pull_up', 'lat_pulldown', 'band_assisted_pull_up'],
  },
  'weighted_pull_up': {
    id: 'weighted_pull_up',
    name: 'Weighted Pull-Up',
    primaryFamily: 'vertical_pull',
    intents: ['strength'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'muscle_up', 'one_arm_pull_up'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['weight_vest', 'dumbbells'],
    difficulty: 'intermediate',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 3,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['pull_up', 'weighted_chin_up', 'lat_pulldown'],
  },
  'chin_up': {
    id: 'chin_up',
    name: 'Chin-Up',
    primaryFamily: 'vertical_pull',
    secondaryFamilies: ['arm_isolation'],
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['pull_up', 'neutral_grip_pull_up', 'lat_pulldown'],
  },
  'neutral_grip_pull_up': {
    id: 'neutral_grip_pull_up',
    name: 'Neutral Grip Pull-Up',
    primaryFamily: 'vertical_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['pull_up', 'chin_up', 'lat_pulldown'],
  },
  'archer_pull_up': {
    id: 'archer_pull_up',
    name: 'Archer Pull-Up',
    primaryFamily: 'vertical_pull',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['one_arm_pull_up', 'front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'advanced',
    progressionStage: 8,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['weighted_pull_up', 'typewriter_pull_up'],
  },
  'band_assisted_pull_up': {
    id: 'band_assisted_pull_up',
    name: 'Band Assisted Pull-Up',
    primaryFamily: 'vertical_pull',
    intents: ['strength'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar', 'resistance_bands'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['lat_pulldown', 'australian_pull_up'],
  },
  'lat_pulldown': {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    primaryFamily: 'vertical_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['lat_pulldown'],
    optionalEquipment: ['cables'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['pull_up', 'band_assisted_pull_up'],
  },
  'scap_pull_up': {
    id: 'scap_pull_up',
    name: 'Scapular Pull-Up',
    primaryFamily: 'scapular_control',
    secondaryFamilies: ['vertical_pull'],
    intents: ['activation', 'durability'],
    primaryIntent: 'activation',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['dead_hang'],
  },

  // =========================================================================
  // HORIZONTAL PULL EXERCISES
  // =========================================================================
  'ring_row': {
    id: 'ring_row',
    name: 'Ring Row',
    primaryFamily: 'horizontal_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['bodyweight_row', 'dumbbell_row', 'cable_row'],
  },
  'bodyweight_row': {
    id: 'bodyweight_row',
    name: 'Bodyweight Row',
    primaryFamily: 'horizontal_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['ring_row', 'dumbbell_row'],
  },
  'low_angle_row': {
    id: 'low_angle_row',
    name: 'Low Angle Row',
    primaryFamily: 'horizontal_pull',
    secondaryFamilies: ['straight_arm_pull'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['ring_row', 'front_lever_row'],
  },
  'dumbbell_row': {
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    primaryFamily: 'horizontal_pull',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    optionalEquipment: ['bench'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['ring_row', 'cable_row', 'bodyweight_row'],
  },
  'cable_row': {
    id: 'cable_row',
    name: 'Cable Row',
    primaryFamily: 'horizontal_pull',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['cables'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['dumbbell_row', 'ring_row'],
  },

  // =========================================================================
  // STRAIGHT ARM PULL (FRONT LEVER FAMILY)
  // =========================================================================
  'tuck_fl': {
    id: 'tuck_fl',
    name: 'Tuck Front Lever Hold',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['rings'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['adv_tuck_fl', 'banded_fl_hold', 'fl_raises'],
  },
  'adv_tuck_fl': {
    id: 'adv_tuck_fl',
    name: 'Advanced Tuck Front Lever Hold',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['rings'],
    difficulty: 'advanced',
    progressionStage: 6,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['tuck_fl', 'one_leg_fl', 'banded_fl_hold'],
  },
  'one_leg_fl': {
    id: 'one_leg_fl',
    name: 'One Leg Front Lever Hold',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['rings'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['adv_tuck_fl', 'straddle_fl'],
  },
  'straddle_fl': {
    id: 'straddle_fl',
    name: 'Straddle Front Lever Hold',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['rings'],
    difficulty: 'elite',
    progressionStage: 8,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['one_leg_fl', 'full_fl'],
  },
  'full_fl': {
    id: 'full_fl',
    name: 'Full Front Lever Hold',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['rings'],
    difficulty: 'elite',
    progressionStage: 10,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 5,
    placementTier: 1,
    substitutionPool: ['straddle_fl'],
  },
  'fl_raises': {
    id: 'fl_raises',
    name: 'Front Lever Raises',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['vertical_pull'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['tuck_fl', 'ice_cream_makers'],
  },
  'ice_cream_makers': {
    id: 'ice_cream_makers',
    name: 'Ice Cream Makers',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['vertical_pull'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['fl_raises'],
  },

  // =========================================================================
  // BACK LEVER FAMILY
  // =========================================================================
  'german_hang': {
    id: 'german_hang',
    name: 'German Hang',
    primaryFamily: 'straight_arm_pull',
    secondaryFamilies: ['mobility', 'scapular_control'],
    intents: ['skill', 'mobility'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever'],
    requiredEquipment: ['rings'],
    optionalEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 2,
    neuralDemand: 3,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['skin_the_cat'],
  },
  'skin_the_cat': {
    id: 'skin_the_cat',
    name: 'Skin the Cat',
    primaryFamily: 'transition',
    secondaryFamilies: ['straight_arm_pull', 'mobility'],
    intents: ['skill', 'mobility'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever', 'muscle_up'],
    requiredEquipment: ['rings'],
    optionalEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 2,
    neuralDemand: 3,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['german_hang'],
  },
  'tuck_bl': {
    id: 'tuck_bl',
    name: 'Tuck Back Lever Hold',
    primaryFamily: 'straight_arm_pull',
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['german_hang', 'adv_tuck_bl'],
  },
  'adv_tuck_bl': {
    id: 'adv_tuck_bl',
    name: 'Advanced Tuck Back Lever Hold',
    primaryFamily: 'straight_arm_pull',
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'advanced',
    progressionStage: 6,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['tuck_bl', 'straddle_bl'],
  },
  'straddle_bl': {
    id: 'straddle_bl',
    name: 'Straddle Back Lever Hold',
    primaryFamily: 'straight_arm_pull',
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'advanced',
    progressionStage: 8,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['adv_tuck_bl', 'full_bl'],
  },
  'full_bl': {
    id: 'full_bl',
    name: 'Full Back Lever Hold',
    primaryFamily: 'straight_arm_pull',
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['back_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'elite',
    progressionStage: 10,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 5,
    placementTier: 1,
    substitutionPool: ['straddle_bl'],
  },

  // =========================================================================
  // HORIZONTAL PUSH (PLANCHE FAMILY)
  // =========================================================================
  'planche_lean': {
    id: 'planche_lean',
    name: 'Planche Lean',
    primaryFamily: 'straight_arm_push',
    secondaryFamilies: ['horizontal_push'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 2,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['pppu', 'tuck_planche'],
  },
  'tuck_planche': {
    id: 'tuck_planche',
    name: 'Tuck Planche Hold',
    primaryFamily: 'straight_arm_push',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['planche_lean', 'adv_tuck_planche', 'banded_planche_hold'],
  },
  'adv_tuck_planche': {
    id: 'adv_tuck_planche',
    name: 'Advanced Tuck Planche Hold',
    primaryFamily: 'straight_arm_push',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 4,
    placementTier: 1,
    substitutionPool: ['tuck_planche', 'straddle_planche'],
  },
  'straddle_planche': {
    id: 'straddle_planche',
    name: 'Straddle Planche Hold',
    primaryFamily: 'straight_arm_push',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'elite',
    progressionStage: 9,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 5,
    placementTier: 1,
    substitutionPool: ['adv_tuck_planche', 'full_planche'],
  },
  'full_planche': {
    id: 'full_planche',
    name: 'Full Planche Hold',
    primaryFamily: 'straight_arm_push',
    secondaryFamilies: ['compression_core'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'elite',
    progressionStage: 10,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 5,
    placementTier: 1,
    substitutionPool: ['straddle_planche'],
  },
  'pppu': {
    id: 'pppu',
    name: 'Pseudo Planche Push-Up',
    primaryFamily: 'horizontal_push',
    secondaryFamilies: ['straight_arm_push'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['planche_lean', 'ring_push_up'],
  },

  // =========================================================================
  // PUSH-UP VARIATIONS
  // =========================================================================
  'push_up': {
    id: 'push_up',
    name: 'Push-Up',
    primaryFamily: 'horizontal_push',
    intents: ['strength', 'endurance'],
    primaryIntent: 'strength',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['diamond_push_up', 'ring_push_up', 'incline_push_up'],
  },
  'diamond_push_up': {
    id: 'diamond_push_up',
    name: 'Diamond Push-Up',
    primaryFamily: 'horizontal_push',
    secondaryFamilies: ['arm_isolation'],
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['planche'],
    requiredEquipment: ['floor'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['push_up', 'close_grip_push_up'],
  },
  'ring_push_up': {
    id: 'ring_push_up',
    name: 'Ring Push-Up',
    primaryFamily: 'horizontal_push',
    secondaryFamilies: ['scapular_control'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['planche', 'muscle_up'],
    requiredEquipment: ['rings'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['push_up', 'pppu'],
  },
  'archer_push_up': {
    id: 'archer_push_up',
    name: 'Archer Push-Up',
    primaryFamily: 'horizontal_push',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['one_arm_push_up', 'planche'],
    requiredEquipment: ['floor'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['ring_push_up', 'weighted_push_up'],
  },

  // =========================================================================
  // VERTICAL PUSH (HSPU FAMILY)
  // =========================================================================
  'pike_push_up': {
    id: 'pike_push_up',
    name: 'Pike Push-Up',
    primaryFamily: 'vertical_push',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['hspu', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['wall_hspu', 'elevated_pike_push_up'],
  },
  'elevated_pike_push_up': {
    id: 'elevated_pike_push_up',
    name: 'Elevated Pike Push-Up',
    primaryFamily: 'vertical_push',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['hspu', 'handstand'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['bench'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['pike_push_up', 'wall_hspu'],
  },
  'wall_hspu': {
    id: 'wall_hspu',
    name: 'Wall Handstand Push-Up',
    primaryFamily: 'vertical_push',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['hspu', 'handstand'],
    requiredEquipment: ['wall'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['elevated_pike_push_up', 'deficit_hspu'],
  },
  'deficit_hspu': {
    id: 'deficit_hspu',
    name: 'Deficit Handstand Push-Up',
    primaryFamily: 'vertical_push',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['hspu', 'handstand'],
    requiredEquipment: ['wall', 'parallettes'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['wall_hspu', 'free_hspu'],
  },
  'free_hspu': {
    id: 'free_hspu',
    name: 'Freestanding Handstand Push-Up',
    primaryFamily: 'vertical_push',
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['hspu', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'elite',
    progressionStage: 9,
    fatigueCost: 5,
    neuralDemand: 5,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['deficit_hspu'],
  },

  // =========================================================================
  // DIP PATTERN
  // =========================================================================
  'dip': {
    id: 'dip',
    name: 'Parallel Bar Dip',
    primaryFamily: 'dip_pattern',
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up', 'planche'],
    requiredEquipment: ['dip_bars'],
    optionalEquipment: ['parallettes'],
    difficulty: 'beginner',
    progressionStage: 4,
    fatigueCost: 3,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['ring_dip', 'bench_dip', 'straight_bar_dip'],
  },
  'weighted_dip': {
    id: 'weighted_dip',
    name: 'Weighted Dip',
    primaryFamily: 'dip_pattern',
    intents: ['strength'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up', 'planche'],
    requiredEquipment: ['dip_bars'],
    optionalEquipment: ['weight_vest', 'dumbbells'],
    difficulty: 'intermediate',
    progressionStage: 6,
    fatigueCost: 4,
    neuralDemand: 2,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['dip', 'ring_dip'],
  },
  'ring_dip': {
    id: 'ring_dip',
    name: 'Ring Dip',
    primaryFamily: 'dip_pattern',
    secondaryFamilies: ['scapular_control'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up', 'iron_cross'],
    requiredEquipment: ['rings'],
    difficulty: 'intermediate',
    progressionStage: 6,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['dip', 'weighted_dip'],
  },
  'straight_bar_dip': {
    id: 'straight_bar_dip',
    name: 'Straight Bar Dip',
    primaryFamily: 'dip_pattern',
    secondaryFamilies: ['transition'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['straight_bar'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['dip', 'korean_dip'],
  },
  'korean_dip': {
    id: 'korean_dip',
    name: 'Korean Dip',
    primaryFamily: 'dip_pattern',
    secondaryFamilies: ['mobility'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up', 'back_lever'],
    requiredEquipment: ['dip_bars'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 4,
    placementTier: 2,
    substitutionPool: ['straight_bar_dip', 'ring_dip'],
  },

  // =========================================================================
  // MUSCLE-UP FAMILY
  // =========================================================================
  'explosive_pull_up': {
    id: 'explosive_pull_up',
    name: 'Explosive Pull-Up',
    primaryFamily: 'explosive_pull',
    secondaryFamilies: ['vertical_pull'],
    intents: ['power', 'skill'],
    primaryIntent: 'power',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 2,
    substitutionPool: ['weighted_pull_up', 'chest_to_bar_pull_up'],
  },
  'chest_to_bar_pull_up': {
    id: 'chest_to_bar_pull_up',
    name: 'Chest-to-Bar Pull-Up',
    primaryFamily: 'vertical_pull',
    secondaryFamilies: ['explosive_pull'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 6,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['pull_up', 'explosive_pull_up'],
  },
  'muscle_up_transition': {
    id: 'muscle_up_transition',
    name: 'Muscle-Up Transition Drill',
    primaryFamily: 'transition',
    secondaryFamilies: ['dip_pattern', 'vertical_pull'],
    intents: ['skill'],
    primaryIntent: 'skill',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    optionalEquipment: ['resistance_bands'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 2,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['negative_muscle_up', 'banded_muscle_up'],
  },
  'negative_muscle_up': {
    id: 'negative_muscle_up',
    name: 'Negative Muscle-Up',
    primaryFamily: 'transition',
    secondaryFamilies: ['dip_pattern', 'vertical_pull'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 6,
    fatigueCost: 3,
    neuralDemand: 4,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['muscle_up_transition', 'bar_muscle_up'],
  },
  'bar_muscle_up': {
    id: 'bar_muscle_up',
    name: 'Bar Muscle-Up',
    primaryFamily: 'transition',
    secondaryFamilies: ['explosive_pull', 'dip_pattern'],
    intents: ['skill', 'power'],
    primaryIntent: 'skill',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'advanced',
    progressionStage: 8,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['negative_muscle_up', 'ring_muscle_up'],
  },
  'ring_muscle_up': {
    id: 'ring_muscle_up',
    name: 'Ring Muscle-Up',
    primaryFamily: 'transition',
    secondaryFamilies: ['explosive_pull', 'dip_pattern'],
    intents: ['skill', 'power'],
    primaryIntent: 'skill',
    skillCarryover: ['muscle_up'],
    requiredEquipment: ['rings'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 5,
    jointStress: 3,
    placementTier: 1,
    substitutionPool: ['bar_muscle_up'],
  },

  // =========================================================================
  // COMPRESSION / L-SIT FAMILY
  // =========================================================================
  'l_sit': {
    id: 'l_sit',
    name: 'L-Sit Hold',
    primaryFamily: 'compression_core',
    secondaryFamilies: ['straight_arm_push'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['l_sit', 'v_sit', 'front_lever', 'planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes', 'dip_bars'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 3,
    jointStress: 2,
    placementTier: 1,
    substitutionPool: ['tuck_l_sit', 'v_sit', 'hanging_leg_raise'],
  },
  'tuck_l_sit': {
    id: 'tuck_l_sit',
    name: 'Tuck L-Sit Hold',
    primaryFamily: 'compression_core',
    intents: ['skill'],
    primaryIntent: 'skill',
    skillCarryover: ['l_sit'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 1,
    substitutionPool: ['l_sit', 'one_leg_l_sit'],
  },
  'v_sit': {
    id: 'v_sit',
    name: 'V-Sit Hold',
    primaryFamily: 'compression_core',
    secondaryFamilies: ['mobility'],
    intents: ['skill', 'strength'],
    primaryIntent: 'skill',
    skillCarryover: ['v_sit', 'l_sit', 'planche'],
    requiredEquipment: ['floor'],
    optionalEquipment: ['parallettes'],
    difficulty: 'advanced',
    progressionStage: 8,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 2,
    placementTier: 1,
    substitutionPool: ['l_sit', 'manna'],
  },
  'hanging_leg_raise': {
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    primaryFamily: 'compression_core',
    secondaryFamilies: ['grip_strength'],
    intents: ['strength', 'hypertrophy'],
    primaryIntent: 'strength',
    skillCarryover: ['l_sit', 'front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['knee_raise', 'toes_to_bar'],
  },
  'toes_to_bar': {
    id: 'toes_to_bar',
    name: 'Toes to Bar',
    primaryFamily: 'compression_core',
    secondaryFamilies: ['grip_strength'],
    intents: ['strength', 'endurance'],
    primaryIntent: 'strength',
    skillCarryover: ['l_sit', 'front_lever'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['hanging_leg_raise', 'knee_raise'],
  },

  // =========================================================================
  // ANTI-EXTENSION CORE
  // =========================================================================
  'hollow_body_hold': {
    id: 'hollow_body_hold',
    name: 'Hollow Body Hold',
    primaryFamily: 'anti_extension_core',
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'planche', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['plank', 'dead_bug'],
  },
  'hollow_body_rock': {
    id: 'hollow_body_rock',
    name: 'Hollow Body Rock',
    primaryFamily: 'anti_extension_core',
    intents: ['strength', 'endurance'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever', 'planche'],
    requiredEquipment: ['floor'],
    difficulty: 'intermediate',
    progressionStage: 4,
    fatigueCost: 2,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 2,
    substitutionPool: ['hollow_body_hold', 'ab_wheel_rollout'],
  },
  'plank': {
    id: 'plank',
    name: 'Plank',
    primaryFamily: 'anti_extension_core',
    intents: ['durability', 'endurance'],
    primaryIntent: 'durability',
    skillCarryover: ['planche', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['hollow_body_hold', 'dead_bug'],
  },
  'ab_wheel_rollout': {
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    primaryFamily: 'anti_extension_core',
    intents: ['strength'],
    primaryIntent: 'strength',
    skillCarryover: ['planche', 'front_lever'],
    requiredEquipment: ['floor'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 3,
    neuralDemand: 2,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['hollow_body_hold', 'dragon_flag'],
  },
  'dragon_flag': {
    id: 'dragon_flag',
    name: 'Dragon Flag',
    primaryFamily: 'anti_extension_core',
    secondaryFamilies: ['compression_core'],
    intents: ['strength', 'skill'],
    primaryIntent: 'strength',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['bench'],
    optionalEquipment: ['floor'],
    difficulty: 'advanced',
    progressionStage: 7,
    fatigueCost: 4,
    neuralDemand: 4,
    jointStress: 2,
    placementTier: 2,
    substitutionPool: ['ab_wheel_rollout', 'hollow_body_hold'],
  },

  // =========================================================================
  // SCAPULAR CONTROL
  // =========================================================================
  'scap_push_up': {
    id: 'scap_push_up',
    name: 'Scapular Push-Up',
    primaryFamily: 'scapular_control',
    intents: ['activation', 'durability'],
    primaryIntent: 'activation',
    skillCarryover: ['planche', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['scap_pull_up'],
  },
  'ring_face_pull': {
    id: 'ring_face_pull',
    name: 'Ring Face Pull',
    primaryFamily: 'scapular_control',
    secondaryFamilies: ['horizontal_pull'],
    intents: ['durability', 'hypertrophy'],
    primaryIntent: 'durability',
    skillCarryover: ['front_lever'],
    requiredEquipment: ['rings'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['band_face_pull', 'rear_delt_fly'],
  },

  // =========================================================================
  // JOINT INTEGRITY / PREHAB
  // =========================================================================
  'wrist_circles': {
    id: 'wrist_circles',
    name: 'Wrist Circles',
    primaryFamily: 'joint_integrity',
    intents: ['durability', 'activation'],
    primaryIntent: 'durability',
    skillCarryover: ['planche', 'handstand'],
    requiredEquipment: ['floor'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['wrist_stretches'],
  },
  'shoulder_dislocates': {
    id: 'shoulder_dislocates',
    name: 'Shoulder Dislocates',
    primaryFamily: 'joint_integrity',
    secondaryFamilies: ['mobility'],
    intents: ['mobility', 'durability'],
    primaryIntent: 'mobility',
    skillCarryover: ['back_lever', 'iron_cross'],
    requiredEquipment: ['resistance_bands'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 2,
    placementTier: 3,
    substitutionPool: ['shoulder_circles'],
  },
  'dead_hang': {
    id: 'dead_hang',
    name: 'Dead Hang',
    primaryFamily: 'joint_integrity',
    secondaryFamilies: ['grip_strength', 'scapular_control'],
    intents: ['durability', 'mobility'],
    primaryIntent: 'durability',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 1,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['active_hang'],
  },
  'active_hang': {
    id: 'active_hang',
    name: 'Active Hang',
    primaryFamily: 'scapular_control',
    secondaryFamilies: ['joint_integrity', 'grip_strength'],
    intents: ['activation', 'durability'],
    primaryIntent: 'activation',
    skillCarryover: ['front_lever', 'muscle_up'],
    requiredEquipment: ['pullup_bar'],
    difficulty: 'beginner',
    progressionStage: 2,
    fatigueCost: 1,
    neuralDemand: 2,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['dead_hang', 'scap_pull_up'],
  },

  // =========================================================================
  // ARM ISOLATION (HYPERTROPHY SUPPORT)
  // =========================================================================
  'bicep_curl': {
    id: 'bicep_curl',
    name: 'Bicep Curl',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['hammer_curl', 'incline_curl', 'ring_curl'],
  },
  'hammer_curl': {
    id: 'hammer_curl',
    name: 'Hammer Curl',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['bicep_curl', 'incline_curl'],
  },
  'incline_curl': {
    id: 'incline_curl',
    name: 'Incline Dumbbell Curl',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells', 'bench'],
    difficulty: 'beginner',
    progressionStage: 4,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['bicep_curl', 'spider_curl'],
  },
  'spider_curl': {
    id: 'spider_curl',
    name: 'Spider Curl',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells', 'bench'],
    difficulty: 'intermediate',
    progressionStage: 5,
    fatigueCost: 2,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['incline_curl', 'bicep_curl'],
  },
  'tricep_pushdown': {
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['cables'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['tricep_extension', 'close_grip_push_up'],
  },
  'overhead_tricep_extension': {
    id: 'overhead_tricep_extension',
    name: 'Overhead Tricep Extension',
    primaryFamily: 'arm_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['tricep_pushdown', 'skull_crusher'],
  },

  // =========================================================================
  // SHOULDER ISOLATION (HYPERTROPHY SUPPORT)
  // =========================================================================
  'lateral_raise': {
    id: 'lateral_raise',
    name: 'Lateral Raise',
    primaryFamily: 'shoulder_isolation',
    intents: ['hypertrophy'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['cable_lateral_raise', 'band_lateral_raise'],
  },
  'rear_delt_fly': {
    id: 'rear_delt_fly',
    name: 'Rear Delt Fly',
    primaryFamily: 'shoulder_isolation',
    secondaryFamilies: ['scapular_control'],
    intents: ['hypertrophy', 'durability'],
    primaryIntent: 'hypertrophy',
    skillCarryover: [],
    requiredEquipment: ['dumbbells'],
    difficulty: 'beginner',
    progressionStage: 3,
    fatigueCost: 1,
    neuralDemand: 1,
    jointStress: 1,
    placementTier: 3,
    substitutionPool: ['ring_face_pull', 'band_pull_apart'],
  },
}

// =============================================================================
// LOOKUP FUNCTIONS
// =============================================================================

/**
 * Get classification for an exercise by ID
 */
export function getExerciseClassification(exerciseId: string): ExerciseClassification | null {
  return EXERCISE_CLASSIFICATIONS[exerciseId] || null
}

/**
 * Get all exercises by movement family
 */
export function getExercisesByFamily(family: MovementFamily): ExerciseClassification[] {
  return Object.values(EXERCISE_CLASSIFICATIONS).filter(
    ex => ex.primaryFamily === family || ex.secondaryFamilies?.includes(family)
  )
}

/**
 * Get all exercises by training intent
 */
export function getExercisesByIntent(intent: TrainingIntent): ExerciseClassification[] {
  return Object.values(EXERCISE_CLASSIFICATIONS).filter(
    ex => ex.intents.includes(intent)
  )
}

/**
 * Get all exercises with skill carryover to a specific skill
 */
export function getExercisesWithCarryover(skill: SkillCarryover): ExerciseClassification[] {
  return Object.values(EXERCISE_CLASSIFICATIONS).filter(
    ex => ex.skillCarryover?.includes(skill)
  )
}

/**
 * Get exercises that can be done with given equipment
 */
export function getExercisesForEquipment(equipment: EquipmentTag[]): ExerciseClassification[] {
  return Object.values(EXERCISE_CLASSIFICATIONS).filter(ex => {
    return ex.requiredEquipment.every(req => equipment.includes(req))
  })
}

/**
 * Get valid substitutions for an exercise
 */
export function getValidSubstitutions(
  exerciseId: string,
  availableEquipment: EquipmentTag[],
  preserveIntent: boolean = true
): ExerciseClassification[] {
  const original = EXERCISE_CLASSIFICATIONS[exerciseId]
  if (!original) return []
  
  // Get all exercises in the same primary family
  const sameFamilyExercises = Object.values(EXERCISE_CLASSIFICATIONS).filter(ex => {
    if (ex.id === exerciseId) return false
    
    // Must be same or related movement family
    const familyMatch = 
      ex.primaryFamily === original.primaryFamily ||
      ex.secondaryFamilies?.includes(original.primaryFamily) ||
      original.secondaryFamilies?.includes(ex.primaryFamily)
    
    if (!familyMatch) return false
    
    // If preserveIntent, must share at least one intent
    if (preserveIntent) {
      const intentMatch = ex.intents.some(intent => original.intents.includes(intent))
      if (!intentMatch) return false
    }
    
    // Must have required equipment
    const hasEquipment = ex.requiredEquipment.every(req => availableEquipment.includes(req))
    if (!hasEquipment) return false
    
    return true
  })
  
  // Sort by:
  // 1. Exercises in the substitutionPool
  // 2. Same difficulty band
  // 3. Similar fatigue cost
  return sameFamilyExercises.sort((a, b) => {
    // Prefer exercises in the substitution pool
    const aInPool = original.substitutionPool?.includes(a.id) ? 1 : 0
    const bInPool = original.substitutionPool?.includes(b.id) ? 1 : 0
    if (aInPool !== bInPool) return bInPool - aInPool
    
    // Prefer same difficulty
    const aSameDifficulty = a.difficulty === original.difficulty ? 1 : 0
    const bSameDifficulty = b.difficulty === original.difficulty ? 1 : 0
    if (aSameDifficulty !== bSameDifficulty) return bSameDifficulty - aSameDifficulty
    
    // Prefer similar fatigue cost
    return Math.abs(a.fatigueCost - original.fatigueCost) - Math.abs(b.fatigueCost - original.fatigueCost)
  })
}

/**
 * Get exercises for time-constrained session prioritization
 * Returns exercises sorted by placement tier (skill/main first, accessories last)
 */
export function prioritizeForTimeConstraint(exercises: ExerciseClassification[]): ExerciseClassification[] {
  return [...exercises].sort((a, b) => {
    // Sort by placement tier (lower = higher priority)
    if (a.placementTier !== b.placementTier) {
      return a.placementTier - b.placementTier
    }
    
    // Then by intent priority (skill > strength > power > others)
    const intentPriority: Record<TrainingIntent, number> = {
      skill: 1,
      strength: 2,
      power: 2,
      hypertrophy: 3,
      endurance: 4,
      durability: 5,
      mobility: 6,
      activation: 0,
      accessory: 5,
    }
    
    return (intentPriority[a.primaryIntent] || 5) - (intentPriority[b.primaryIntent] || 5)
  })
}

/**
 * Check if an exercise can compress (be removed in time-limited sessions)
 */
export function canCompressExercise(exerciseId: string): boolean {
  const classification = EXERCISE_CLASSIFICATIONS[exerciseId]
  if (!classification) return true
  
  // Check if the primary intent is compressible
  const intentMeta = TRAINING_INTENT_METADATA[classification.primaryIntent]
  return intentMeta?.canCompress ?? true
}
