/**
 * Canonical Explanation Types
 * 
 * Single source of truth for program/session explanation metadata.
 * These types are used by the generator to produce explanations,
 * and by the UI to render them truthfully.
 * 
 * CRITICAL: Every explanation must be grounded in real engine data.
 * Do NOT add explanation text that cannot be derived from reason codes.
 */

// =============================================================================
// REASON CODES - Machine-readable, generated by real engine decisions
// =============================================================================

/**
 * Program-level reason codes explaining why the program was structured this way.
 * Each code corresponds to a specific engine decision point.
 */
export type ProgramReasonCode =
  // Goal-related
  | 'primary_goal_direct'           // Exercise directly trains primary goal
  | 'secondary_goal_support'        // Exercise supports secondary goal
  // Weak point / limiter
  | 'weak_point_support'            // Added to address detected weak point
  | 'limiter_support'               // Added to address skill limiter
  // Progression state
  | 'progression_advance'           // Ready to progress based on performance
  | 'progression_hold'              // Maintaining current level
  | 'progression_regress'           // Stepping back for recovery/technique
  // Fatigue / recovery
  | 'fatigue_high_reduce_volume'    // High fatigue detected, volume reduced
  | 'fatigue_moderate_maintain'     // Moderate fatigue, maintaining load
  | 'fatigue_stable'                // Fatigue under control
  | 'recovery_bias_session'         // Session designed for active recovery
  // Flexible scheduling
  | 'flexible_frequency_contract'   // Reduced days this week
  | 'flexible_frequency_expand'     // Added days this week
  | 'flexible_frequency_maintain'   // Keeping current frequency
  | 'static_schedule_locked'        // User chose fixed schedule
  // Movement intelligence
  | 'joint_stress_downrank'         // Exercise downranked due to joint stress
  | 'straight_arm_load_control'     // Managing straight-arm volume
  | 'bent_arm_balance'              // Balancing bent-arm work
  // Pattern support
  | 'vertical_push_support'         // Vertical pressing for goal support
  | 'horizontal_push_support'       // Horizontal pressing for goal support
  | 'vertical_pull_support'         // Vertical pulling for goal support
  | 'horizontal_pull_support'       // Horizontal pulling for goal support
  | 'straight_arm_pull_support'     // Straight-arm pulling (FL work)
  | 'straight_arm_push_support'     // Straight-arm pushing (planche work)
  | 'compression_support'           // Compression strength for L-sit/V-sit
  | 'anti_extension_support'        // Anti-extension for lever/dragon flag
  | 'scapular_control_support'      // Scapular work for skill stability
  // Session structure
  | 'high_neural_session'           // Primary skill/strength focus
  | 'lower_fatigue_session'         // Lighter load to preserve recovery
  | 'skill_transfer_priority'       // Exercises chosen for skill carryover
  | 'time_budget_constraint'        // Limited by session time
  | 'equipment_constraint'          // Limited by available equipment
  // Stability reasons
  | 'no_change_stability'           // Program stable, no changes needed
  | 'no_progress_incomplete_data'   // Not enough data to progress
  | 'consistency_maintained'        // Keeping consistent structure

/**
 * Session-level reason codes for individual workout explanations
 */
export type SessionReasonCode =
  | 'skill_primary_day'             // Primary skill work day
  | 'strength_primary_day'          // Primary strength work day
  | 'balanced_session'              // Mix of skill and strength
  | 'recovery_active_day'           // Active recovery session
  | 'volume_reduced_fatigue'        // Volume cut due to fatigue
  | 'intensity_preserved'           // Kept intensity, reduced volume
  | 'exercise_swap_equipment'       // Exercise swapped for equipment
  | 'exercise_swap_progression'     // Exercise swapped for progression
  | 'support_limiter_specific'      // Support work for specific limiter
  | 'core_compression_included'     // Compression core added
  | 'core_anti_extension_included'  // Anti-extension core added
  | 'deload_session'                // Deload week session
  | 'comeback_reduced'              // Reduced load after break

/**
 * Change reason codes for comparing versions
 */
export type ChangeReasonCode =
  | 'first_generation'              // Initial program, no comparison
  | 'fatigue_adjustment'            // Changed due to fatigue state
  | 'limiter_shifted'               // Primary limiter changed
  | 'schedule_contracted'           // Fewer days this week
  | 'schedule_expanded'             // More days this week
  | 'progression_updated'           // Exercise progressions changed
  | 'joint_stress_adjustment'       // Joint stress concerns addressed
  | 'feedback_driven'               // Changed based on workout feedback
  | 'no_change_required'            // Program kept same deliberately
  | 'stability_maintained'          // Stable performance, no change

// =============================================================================
// EXPLANATION METADATA STRUCTURES
// =============================================================================

/**
 * Exercise-level explanation attached to each selected exercise
 */
export interface ExerciseExplanation {
  exerciseId: string
  displayName: string
  reasonCodes: ProgramReasonCode[]
  shortReason: string | null  // Resolved from reason codes, null if not yet resolved
}

/**
 * Session/day-level explanation
 */
export interface SessionExplanation {
  dayKey: string              // e.g., "day_1"
  dayNumber: number
  title: string               // e.g., "Day 1: Skill Focus"
  primaryIntent: string       // e.g., "Front Lever Development"
  reasonCodes: SessionReasonCode[]
  whyThisDay: string | null   // Short explanation, resolved from codes
  whyLighterOrHeavier?: string
  limiterSupport?: string[]   // Specific limiters addressed
  exerciseExplanations: ExerciseExplanation[]
}

/**
 * Week structure explanation
 */
export interface WeekStructureExplanation {
  currentWeekFrequency: number
  scheduleMode: 'static' | 'flexible'
  reasonCodes: ProgramReasonCode[]
  rationale: string | null
  stressDistributionReason?: string
  comparedToPrevious?: {
    previousFrequency: number
    frequencyChange: 'same' | 'increased' | 'decreased'
    changeReason?: string
  }
}

/**
 * Change summary for regenerate/adjust flows
 */
export interface ChangeExplanation {
  changed: boolean
  reasonCodes: ChangeReasonCode[]
  majorReasons: string[]      // Resolved human-readable reasons
  preservedReasons?: string[] // What stayed the same and why
  comparedToVersion?: string  // ID of previous program version
}

/**
 * Top-level program explanation metadata
 * Attached to AdaptiveProgram during generation
 */
export interface ProgramExplanationMetadata {
  // Summary section
  summary: {
    primaryGoalReason: string
    scheduleReason?: string
    progressionReason?: string
    recoveryReason?: string
  }
  
  // Week structure
  weekStructure: WeekStructureExplanation
  
  // Per-session explanations
  sessionExplanations: SessionExplanation[]
  
  // Change tracking (for regenerate)
  changeExplanation?: ChangeExplanation
  
  // Metadata
  generatedAt: string
  dataConfidence: 'none' | 'low' | 'medium' | 'high'
  trustedWorkoutCount: number
}

// =============================================================================
// REASON CODE TO TEXT MAPPING
// =============================================================================

/**
 * Maps program reason codes to concise, user-readable text.
 * These are templates that can be customized with context.
 */
export const PROGRAM_REASON_TEXT: Record<ProgramReasonCode, string> = {
  primary_goal_direct: 'Directly trains your primary goal',
  secondary_goal_support: 'Supports secondary training focus',
  weak_point_support: 'Addresses a detected weak point',
  limiter_support: 'Targets a skill limiter',
  progression_advance: 'Ready to progress based on recent performance',
  progression_hold: 'Maintaining current level while building consistency',
  progression_regress: 'Stepped back for better technique or recovery',
  fatigue_high_reduce_volume: 'Volume reduced due to elevated fatigue',
  fatigue_moderate_maintain: 'Maintaining load while monitoring fatigue',
  fatigue_stable: 'Fatigue levels support planned training',
  recovery_bias_session: 'Designed for active recovery',
  flexible_frequency_contract: 'Fewer sessions this week based on recovery',
  flexible_frequency_expand: 'Added sessions based on readiness',
  flexible_frequency_maintain: 'Current frequency matches your recovery state',
  static_schedule_locked: 'Fixed schedule as selected',
  joint_stress_downrank: 'Adjusted for joint stress management',
  straight_arm_load_control: 'Managing straight-arm training volume',
  bent_arm_balance: 'Balancing bent-arm strength work',
  vertical_push_support: 'Vertical pressing for overhead strength',
  horizontal_push_support: 'Horizontal pressing for pushing power',
  vertical_pull_support: 'Vertical pulling for pull-up/lever strength',
  horizontal_pull_support: 'Horizontal pulling for row strength',
  straight_arm_pull_support: 'Straight-arm pulling for lever control',
  straight_arm_push_support: 'Straight-arm pushing for planche development',
  compression_support: 'Compression work for L-sit/V-sit',
  anti_extension_support: 'Anti-extension for body position control',
  scapular_control_support: 'Scapular work for shoulder stability',
  high_neural_session: 'High neural demand skill work',
  lower_fatigue_session: 'Lower fatigue to support recovery',
  skill_transfer_priority: 'Chosen for skill carryover',
  time_budget_constraint: 'Optimized for available session time',
  equipment_constraint: 'Adapted to available equipment',
  no_change_stability: 'Training is progressing well',
  no_progress_incomplete_data: 'Building data for smarter adaptation',
  consistency_maintained: 'Keeping proven structure',
}

export const SESSION_REASON_TEXT: Record<SessionReasonCode, string> = {
  skill_primary_day: 'Primary skill development focus',
  strength_primary_day: 'Primary strength building focus',
  balanced_session: 'Balanced skill and strength work',
  recovery_active_day: 'Active recovery session',
  volume_reduced_fatigue: 'Volume reduced for recovery',
  intensity_preserved: 'Intensity preserved, volume managed',
  exercise_swap_equipment: 'Exercise adapted for equipment',
  exercise_swap_progression: 'Exercise adjusted for progression',
  support_limiter_specific: 'Support work for specific limiter',
  core_compression_included: 'Compression core for skill support',
  core_anti_extension_included: 'Anti-extension for body control',
  deload_session: 'Planned lighter session',
  comeback_reduced: 'Eased load after training break',
}

export const CHANGE_REASON_TEXT: Record<ChangeReasonCode, string> = {
  first_generation: 'Initial program generation',
  fatigue_adjustment: 'Adjusted based on fatigue state',
  limiter_shifted: 'Focus shifted to new limiter',
  schedule_contracted: 'Reduced days this week',
  schedule_expanded: 'Added days this week',
  progression_updated: 'Progressions updated',
  joint_stress_adjustment: 'Adjusted for joint health',
  feedback_driven: 'Adapted from workout feedback',
  no_change_required: 'No change needed',
  stability_maintained: 'Maintaining stable program',
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Resolve reason codes to a single short explanation string
 */
export function resolveReasonCodesToText(
  codes: ProgramReasonCode[],
  maxReasons: number = 2
): string {
  if (codes.length === 0) return ''
  
  // Prioritize the most important reasons
  const priorityOrder: ProgramReasonCode[] = [
    'primary_goal_direct',
    'weak_point_support',
    'limiter_support',
    'progression_advance',
    'fatigue_high_reduce_volume',
    'joint_stress_downrank',
    'skill_transfer_priority',
  ]
  
  // Sort by priority
  const sorted = [...codes].sort((a, b) => {
    const aIdx = priorityOrder.indexOf(a)
    const bIdx = priorityOrder.indexOf(b)
    if (aIdx === -1 && bIdx === -1) return 0
    if (aIdx === -1) return 1
    if (bIdx === -1) return -1
    return aIdx - bIdx
  })
  
  const topReasons = sorted.slice(0, maxReasons)
  return topReasons.map(code => PROGRAM_REASON_TEXT[code]).join('. ')
}

/**
 * Resolve session reason codes to text
 */
export function resolveSessionReasonCodesToText(
  codes: SessionReasonCode[],
  maxReasons: number = 1
): string {
  if (codes.length === 0) return ''
  const topReasons = codes.slice(0, maxReasons)
  return topReasons.map(code => SESSION_REASON_TEXT[code]).join('. ')
}

/**
 * Resolve change reason codes to text
 */
export function resolveChangeReasonCodesToText(
  codes: ChangeReasonCode[]
): string[] {
  return codes
    .filter(code => code !== 'first_generation')
    .map(code => CHANGE_REASON_TEXT[code])
}

/**
 * Check if explanation metadata is valid and grounded
 */
export function validateExplanationMetadata(
  metadata: Partial<ProgramExplanationMetadata>
): { isValid: boolean; issues: string[] } {
  const issues: string[] = []
  
  if (!metadata.summary?.primaryGoalReason) {
    issues.push('Missing primary goal reason')
  }
  
  if (!metadata.weekStructure) {
    issues.push('Missing week structure explanation')
  }
  
  if (!metadata.sessionExplanations || metadata.sessionExplanations.length === 0) {
    issues.push('Missing session explanations')
  }
  
  // Check that reason codes are valid
  metadata.sessionExplanations?.forEach((session, idx) => {
    if (!session.reasonCodes || session.reasonCodes.length === 0) {
      issues.push(`Session ${idx + 1} has no reason codes`)
    }
  })
  
  return {
    isValid: issues.length === 0,
    issues,
  }
}
