-- ============================================================================
-- DOCTRINE BATCH 3 — UPLOADED PDF DOCTRINE (SOURCE REGISTRY ONLY)
-- ============================================================================
-- Mirrors the source registrations in
--   lib/doctrine/source-batches/batch-03-uploaded-pdf-doctrine.ts
--
-- The in-code file is the FALLBACK; this SQL seed is the LIVE/PRIMARY truth
-- consumed by lib/doctrine-runtime-contract.ts via lib/doctrine-db.ts.
--
-- Provenance: every row is paraphrased from prompt Section 5 of the
-- "DOCTRINE BATCH 3" prompt. Raw PDFs were not attached. evidence_snippet is
-- intentionally NULL so a future refinement pass can populate verbatim quotes
-- when PDFs are attached.
--
-- Strictly additive. ON CONFLICT DO NOTHING. Idempotent.
-- ============================================================================

BEGIN;

INSERT INTO training_doctrine_sources (
  id, source_key, title, source_type, description, version, is_active,
  ingestion_status, author, primary_domain,
  secondary_domains_json, style_tags_json, athlete_level_bias_json,
  skill_bias_json, equipment_bias_json, program_type_bias_json,
  method_bias_json, confidence_weight_default,
  notes_on_scope, notes_on_limits
) VALUES
  ('src_batch_03_lower_body_a_dup',
   'lower_body_a_uploaded_pdf_batch_03_duplicate_confirmation',
   'Lower Body Workout A — duplicate confirmation (uploaded PDF)',
   'extracted_pdf',
   'Repeats Lower Body A level progression (pistol box, glute-ham hinge, wall squat, calf raises). Increases provenance/confidence; does not duplicate visible blocks.',
   'v1', TRUE, 'fully_extracted', NULL, 'progression_selection_logic',
   '["progression_selection_logic","bodyweight_strength","duplicate_confirmation","unilateral_logic"]'::jsonb,
   '["bodyweight","unilateral","progression_levels","duplicate_confirmation"]'::jsonb,
   '["beginner","intermediate"]'::jsonb,
   '[]'::jsonb,
   '["box","wall","none"]'::jsonb,
   '["upper_lower","full_body","push_pull_legs"]'::jsonb,
   '["straight_set","tempo"]'::jsonb,
   0.7,
   'Duplicate confirmation of Batch 1 / Batch 2 Lower Body A doctrine.',
   'Must increase confidence/provenance only. Must NOT duplicate visible lower-body blocks.'),

  ('src_batch_03_mz_intermediate_weighted',
   'mz_intermediate_weighted_calisthenics_uploaded_pdf_batch_03',
   'MZ Intermediate Weighted Calisthenics (uploaded PDF)',
   'extracted_pdf',
   'Stage-1 weekly cycle for intermediate weighted dip/pull-up athletes. Heavy 3x3 RIR 0–2 Mon, paused/deadstop assistance 3x3–6 RIR 0–2 Tue, single-set PR 3–6 reps RIR 0 Fri. PR-set drives load increment.',
   'v1', TRUE, 'fully_extracted', NULL, 'weighted_calisthenics',
   '["progression_logic","autoregulation_logic","method_logic","prescription_logic"]'::jsonb,
   '["weighted","intermediate","heavy_assistance_pr","autoregulation"]'::jsonb,
   '["intermediate"]'::jsonb,
   '["weighted_pull_up","weighted_dip"]'::jsonb,
   '["pull_up_bar","dip_bars","weight_belt"]'::jsonb,
   '["push_pull_legs","upper_lower"]'::jsonb,
   '["straight_set"]'::jsonb,
   0.85,
   'Intermediate weighted progression with heavy/PR linkage and assistance independence.',
   'Gated by 15+ pull-up / 20+ dip bodyweight prerequisite. Avoid for true beginners.'),

  ('src_batch_03_forearm_health_dup',
   'forearm_health_uploaded_pdf_batch_03_duplicate_confirmation',
   'Forearm Health — duplicate confirmation (uploaded PDF)',
   'extracted_pdf',
   'Confirms wrist pronation, extension, supination, flexion at 2x15 with short rest. Increases prehab confidence; does not duplicate visible prehab blocks.',
   'v1', TRUE, 'fully_extracted', NULL, 'recovery_protection_logic',
   '["accessory_logic","warmup_logic","duplicate_confirmation"]'::jsonb,
   '["prehab","tendon_support","duplicate_confirmation"]'::jsonb,
   '["beginner","intermediate","advanced"]'::jsonb,
   '["planche","front_lever","one_arm_pull_up","rings_skills"]'::jsonb,
   '["light_db","band","none"]'::jsonb,
   '["any"]'::jsonb,
   '["paired_set","circuit","superset"]'::jsonb,
   0.8,
   'Third independent source confirming wrist circuit dosage.',
   'Source-confidence boost only. Does not produce duplicate visible prehab blocks.'),

  ('src_batch_03_kinevo_bw_foundation',
   'kinevo_bodyweight_strength_foundation_uploaded_pdf_batch_03',
   'Kinevo Bodyweight Strength Foundation (uploaded PDF)',
   'extracted_pdf',
   'Upper-body calisthenics strength foundation built through leverage manipulation. Bands recommended <8 pull-ups; free-weight progression viable >8 pull-ups. Pull-up bar required minimum.',
   'v1', TRUE, 'fully_extracted', NULL, 'foundation_building',
   '["progression_logic","equipment_logic","selection_logic"]'::jsonb,
   '["calisthenics","leverage","foundation","upper_body","equipment_aware"]'::jsonb,
   '["beginner","intermediate"]'::jsonb,
   '["pull_up","muscle_up","front_lever","planche"]'::jsonb,
   '["pull_up_bar","resistance_band","dip_bars","rings"]'::jsonb,
   '["full_body","upper_lower","push_pull_legs"]'::jsonb,
   '["straight_set","tempo"]'::jsonb,
   0.8,
   'Bodyweight calisthenics strength foundation with leverage-first progression.',
   'Free-weight loading only above 8-rep pull-up threshold. Below 8, bands lead.'),

  ('src_batch_03_no_bs_nutrition',
   'no_bs_nutrition_system_uploaded_pdf_batch_03',
   'No-BS Nutrition System (uploaded PDF)',
   'extracted_pdf',
   'Adherence-first nutrition. Calories + protein + consistency dominate over obsessive macro tracking. Strategic cheat meals tolerated. Not medical advice. Does not override training generation.',
   'v1', TRUE, 'fully_extracted', NULL, 'nutrition_adherence_system',
   '["nutrition_logic","adherence_logic","recovery_logic"]'::jsonb,
   '["nutrition","adherence","calories","protein","consistency"]'::jsonb,
   '["beginner","intermediate","advanced"]'::jsonb,
   '[]'::jsonb,
   '["any"]'::jsonb,
   '["any"]'::jsonb,
   '["any"]'::jsonb,
   0.7,
   'Adherence-first nutrition framing for muscle gain / leanness.',
   'Supportive only. Cannot frame as medical advice. Cannot override training generation.'),

  ('src_batch_03_bsf_training_log',
   'bsf_training_log_warmup_hypertrophy_uploaded_pdf_batch_03',
   'BSF Training Log — Warm-up / Hypertrophy Phase 1 (uploaded PDF)',
   'extracted_pdf',
   'Upper-body warm-up sequence (8 minimal-rest pieces). Phase-1 hypertrophy structure: 3 weekly sessions, 1+ rest day between, progression held constant while reps/sets advance week-to-week. Hybrid skill/hypertrophy selection.',
   'v1', TRUE, 'fully_extracted', NULL, 'hypertrophy_phase',
   '["warmup_logic","progression_stability_logic","selection_logic"]'::jsonb,
   '["hypertrophy","warmup","phase1","skill_hybrid"]'::jsonb,
   '["beginner","intermediate"]'::jsonb,
   '["planche","front_lever","handstand"]'::jsonb,
   '["pull_up_bar","parallettes","band","rings"]'::jsonb,
   '["push_pull_legs","upper_lower","full_body"]'::jsonb,
   '["straight_set","tempo"]'::jsonb,
   0.8,
   'Phase-1 hypertrophy with progression stability and skill/hypertrophy hybrid selection.',
   'Progression variant must remain constant within Phase 1; reps/sets advance only.'),

  ('src_batch_03_ian_barseagle_weighted',
   'ian_barseagle_weighted_bodyweight_calisthenics_uploaded_pdf_batch_03',
   'Ian Barseagle Weighted & Bodyweight Calisthenics (uploaded PDF)',
   'extracted_pdf',
   'Bodyweight prerequisite ramp: 1–3 reps → 6–8 sets low-reps 3–4 min rest → 8 reps → 3–4 max-rep sets 5–6 min rest → 15+ reps unlocks weighted plan. Movement-specific warm-up incl. ~50% working-load reps; rest scales with warm-up load.',
   'v1', TRUE, 'fully_extracted', NULL, 'weighted_calisthenics',
   '["progression_logic","warmup_logic","prescription_logic","prerequisite_logic"]'::jsonb,
   '["weighted","bodyweight_prereq","ramp_warmup","movement_specific"]'::jsonb,
   '["beginner","intermediate","advanced"]'::jsonb,
   '["pull_up","weighted_pull_up","weighted_dip"]'::jsonb,
   '["pull_up_bar","dip_bars","weight_belt","band"]'::jsonb,
   '["push_pull_legs","upper_lower"]'::jsonb,
   '["straight_set"]'::jsonb,
   0.85,
   'Pull-up / dip prerequisite ramp and weighted-day movement-specific warm-up.',
   'Heavy weighted plan gated by 15+ strict pull-ups and 20+ strict dips.'),

  ('src_batch_03_flexibility_notes',
   'flexibility_notes_uploaded_pdf_batch_03',
   'Flexibility Notes — Active vs Passive, Skill Support, Planche Wrist (uploaded PDF)',
   'extracted_pdf',
   'Active vs passive flexibility, mobility = active movement, skill needs active flexibility, planche forward-lean wrist stress, V-sit/manna/hollowback need flexibility-loaded compression. Reduces injury risk; does not eliminate it.',
   'v1', TRUE, 'fully_extracted', NULL, 'flexibility_mobility',
   '["mobility_logic","prehab_logic","skill_eligibility_logic"]'::jsonb,
   '["flexibility","mobility","planche_wrist","skill_support"]'::jsonb,
   '["beginner","intermediate","advanced"]'::jsonb,
   '["planche","handstand","manna","v_sit","hollowback"]'::jsonb,
   '["parallettes","mat","band","none"]'::jsonb,
   '["any"]'::jsonb,
   '["circuit","paired_set","skill_practice"]'::jsonb,
   0.85,
   'Mobility/flexibility doctrine; informs warm-up, skill eligibility, planche prehab.',
   'Cannot claim flexibility eliminates injury risk. Pain rules still override.'),

  ('src_batch_03_mns_pyramid',
   'muscle_strength_pyramid_training_uploaded_pdf_batch_03',
   'Muscle & Strength Pyramid (Training) (uploaded PDF)',
   'extracted_pdf',
   'Helms-style hierarchy: adherence → volume/intensity/frequency → progression → exercise selection → rest/tempo. Acts as high-level conflict resolution; yields to skill-specific calisthenics doctrine when domain matches.',
   'v1', TRUE, 'fully_extracted', NULL, 'pyramid_priority_hierarchy',
   '["priority_logic","autoregulation_logic","selection_logic","rest_logic","tempo_logic"]'::jsonb,
   '["pyramid","adherence","vif","autoregulation","conflict_resolution"]'::jsonb,
   '["beginner","intermediate","advanced"]'::jsonb,
   '[]'::jsonb,
   '["any"]'::jsonb,
   '["any"]'::jsonb,
   '["any"]'::jsonb,
   0.9,
   'High-level conflict resolution and prioritization hierarchy.',
   'Yields to skill-specific calisthenics doctrine when the specific source is more directly applicable.')
ON CONFLICT (id) DO NOTHING;

COMMIT;
